### ISSUE TITLE
Is only one client allowed to access at a time?

### ISSUE THREAD

**Issue by ltinerary** [Xpra-org/xpra-html5#100]
I start a Xpra service by `xpra start --start=xterm --bind-tcp=0.0.0.0:10001` 【ubuntu18.04】,

Then I use a browser to access it.

And it worked.

But when I use another browser to access，

The previous browser exits to the login page.

Is only one client allowed to access at a time?

What should I do if I want simultaneous access？

Thanks.

**Comment by totaam** [comment]
> What should I do if I want simultaneous access？

Did you enable sharing from the connect page's `Advanced Options` for both clients?

**Comment by ltinerary** [comment]
> Did you enable sharing from the connect page's `Advanced Options` for both clients?

Thanks for your reply.

According to your suggestion，every browser can access the remote service.

But they update at the same time,

This is not what I expected.

**I want each client to be independent with only one Xpra service.**

Do you have any Settings for this?

Also,I found in the client Login page, 

there can enter the username and password.

I think this username and password is for logging in to the remote host and this can  make each client independent.

But it doesn't seem to.

And,if i didn't enter the password,it also can connect the xPra service. 

Here, I use different user to connect.
![image](https://user-images.githubusercontent.com/79144923/135373335-d1088ccc-dd33-49f6-b282-85583519a2df.png)
![image](https://user-images.githubusercontent.com/79144923/135373400-5eb77077-9945-4de0-ac6f-1353f03f6ec7.png)

**Comment by totaam** [comment]
> I want each client to be independent with only one Xpra service.

It is called an _xpra session_, not service.

Obviously, if you start a single session via `xpra start` then that's the session that every xpra-html5 client can connect to.

If you want each html5 client to have its own session, either run `xpra start` in advance for each one of them and give them individual ports to connect to, or use the system wide proxy server and configure authentication according to your needs:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Proxy-Server.md

(this question is not related to the html5 client - you will encounter the same issues with the regular client)

**Comment by ltinerary** [comment]
Thank you very much.
