### ISSUE TITLE
html5 client not working in Iframe - Utilities.js bugfix not working

### ISSUE THREAD

**Issue by habakuk1979** [Xpra-org/xpra-html5#119]
As in "use html5 client inside an iframe Xpra-org/xpra-html5#118" mentioned the changes of the Utilities.js file cannot be made in my case.
my Utiltities.js under `/usr/local/share/xpra/www/js` looks like this:

`"use strict";var Utilities={VERSION:"4.5.2",REVISION:1087,LOCAL_MODIFICATIONS:5,BRANCH:"master",exc:function(){console&&console.error.apply(console,arguments)},error:function(){console&&console.error.apply(console,arguments)},warn:function(){console&&console.log.apply(console,arguments)},log:function(){console&&console.log.apply(console,arguments)},debug:function(){console&&console.debug.apply(console,arguments)},cexc:function(){console&&console.error.apply(console,arguments)},cerror:function(){console&&console.error.apply(console,arguments)},cwarn:function(){console&&console.log.apply(console,arguments)},clog:function(){console&&console.log.apply(console,arguments)},cdebug:function(){console&&console.debug.apply(console,arguments)},getHexUUID:function(){for(var s=[],hexDigits="0123456789abcdef",i=0;i<36;i++)s[i]=8==i||13==i||18==i||23==i?"-":hexDigits.substr(Math.floor(16*Math.random()),1);return s.join("")},getSecureRandomString:function(len){var crypto=window.crypto||window.mscrypto;if(!crypto){for(var s="";s.length<len;)s+=Utilities.getHexUUID();return s.substr(0,len)}var u=new Uint8Array(len);return crypto.getRandomValues(u),String.fromCharCode.apply(null,u)},xorString:function(str1,str2){var result="";if(str1.length!==str2.length)throw"strings must be equal length";for(var i=0;i<str1.length;i++)result+=String.fromCharCode(str1[i].charCodeAt(0)^str2[i].charCodeAt(0));return result},trimString:function(str,trimLength){return str.length>trimLength?str.substring(0,trimLength-3)+"...":str},getPlatformProcessor:function(){return navigator.oscpu?navigator.oscpu:navigator.hasOwnProperty("cpuClass")?navigator.cpuClass:"unknown"},getPlatformName:function(){return navigator.appVersion.includes("Win")?"Microsoft Windows":navigator.appVersion.includes("Mac")?"Mac OSX":navigator.appVersion.includes("Linux")?"Linux":n "Utilities.js" [noeol] 1L, 12045C 1,113 All`

I launch the xpra server with:

`sudo xpra start --start=foxtrotgps --bind-tcp=192.168.6.4:10000`

I can display my xx.xx.xx.xx:10000 in the browser but I cannot display it in an iframe!

Can some one please help me on this issue as I am an newbee in xpra.

**Comment by totaam** [comment]
> my `Utiltities.js` under `/usr/local/share/xpra/www/js` looks like this:

What OS, distribution and package? What version?
Why is it installed in `/usr/local`?
What is the error that you're seeing?
etc..

**Comment by habakuk1979** [comment]
.I am on ubuntu 18.04 kernel 5.14.19:

I did:
```
git clone https://github.com/Xpra-org/xpra; cd xpra
python3 ./setup.py install
```

and:
```
git clone https://github.com/Xpra-org/xpra-html5
cd xpra-html5
./setup.py install /usr/share/xpra/www
```
and the dependencies as recommended: 

`Build and runtime requirements
apt-get install libx11-dev libxtst-dev libxcomposite-dev libxdamage-dev libxres-dev \
                libxkbfile-dev \
                python-all-dev \
                pandoc \
                libsystemd-dev
GTK3 for the server and GUI client:

apt-get install libgtk-3-dev python3-dev python3-cairo-dev python-gi-dev cython3 
Also install some X11 utilities if not installed already:

apt-get install xauth x11-xkb-utils
To be able to run xpra, you are likely to need:

apt-get install xvfb python3-cairo python3-gi-cairo \
    python3-opengl python3-lz4 python3-rencode python3-pil`
but I had to change it to:
`./setup.py install /usr/local/share/xpra/www`

because otherwise, when installed under   /usr/share/xpra/www  
xpra could not find  html5 client, interestingly. no it works!

**Comment by totaam** [comment]
> but I had to change it to:

That's because you're installing xpra into `/usr/local/` too.
If you install xpra from an official package, or using `--prefix=/usr` (as per https://github.com/Xpra-org/xpra/commit/866a0e1df10275ffae0a9758e610a7a21d9bb825) then this should not be needed.

Now, that you have a source installation. You could patch `Utilities.js` before you install the `xpra-html5` client.
But since the fix from #118 is already in git master, that's unlikely to help.
I think it's best if you look at your Javascript console and post the actual problem with the html5 client.
(it may not be the same as the ticket above)

**Comment by habakuk1979** [comment]
I fear that my utilities.js from 

`usr/local/share/xpra/www/js`

is not what it is suppossed to be. In this bugfix from "use html5 client inside an iframe #118" they are referring to line 439 but my utilities.js hods only about 30lines (see above)??

Are we talking about two different things here?

**Comment by totaam** [comment]
`Utilities.js` lives in `./html5/js/`: https://github.com/Xpra-org/xpra-html5/blob/master/html5/js/Utilities.js

That's where you should make any changes, *before* installing it which is the step where it gets minified down to ~30 lines.

But as I also said before, that's not going to help you since the fix has already been merged.
Try to figure out what the actual error is instead. The javascript console is the place to start.

**Comment by habakuk1979** [comment]
ok thank you:
this is my javascript console, which is in fact a template node of node-red:

`<div style="width: 100%; height:100%">
    <iframe id="iframe" style="width: 100%; height:100%" src=""></iframe>
</div>

<script> 
    (function(scope) {
        // Watch for messages being send to this template node
        scope.$watch('msg', function (msg) {      
            if (msg) {

                var iframe = document.getElementById('iframe');
                iframe.src = msg.payload; // + "?autoplay=1;start=2";
            }       
         }); 
    })(scope); 
</script>`

**Comment by totaam** [comment]
This is not a javascript console and I simply don't have time to teach you all the things you would need to work on this.

My only guess at this point is that you may need to remove or tweak the content security policy:
https://github.com/Xpra-org/xpra/blob/master/fs/etc/xpra/http-headers/10_content_security_policy.txt
