### ISSUE TITLE
sudo xpra changes .Xauthority to root:root

### ISSUE THREAD

**Issue by habakuk1979** [Xpra-org/xpra-html5#121]
Hello!

when I start xpra as sudo (sudo xpra .....) it seems to change the .X authority file (and possible something else too) to root:root owner.

This is what puts you in the well known login - loop after the next reboot. (this is fixed by chown .......)

This happens everytime after reboot when you have startet sudo xpra once.
If you start xpra without sudo it does NOT happen.

Can somebody please tell me how to make sudo xpra change this behaviour?

**Comment by totaam** [comment]
Don't run xpra as root. Just don't.
