### ISSUE TITLE
Session Information («Information → Session Info») always empty.

### ISSUE THREAD

**Issue by belonesox** [Xpra-org/xpra-html5#124]
Session Information («Information → Session Info») always empty for me.
![image](https://user-images.githubusercontent.com/1609739/144731775-2dff049d-5619-4e9f-b338-379a91b53c78.png)

I run server session like that 
```
/usr/bin/xpra start :100 --start=gnome-terminal -d auth --bind-tcp=0.0.0.0:10000,auth=password:value=mysecret --html=/usr/share/xpra/www/ --sharing=yes --microphone=off --terminate-children=yes --speaker=disabled --bell=no --clipboard=yes --notifications=no --av-sync=no --tray=no --mousewheel=on   --daemon=no  -d stats
```

Is I missed something in server options?

xpra-html5 v4.5.2 on commit 6e000d12879f171d1ec7c8ad04a4e40b9df4a79a

**Comment by totaam** [comment]
What is your xpra server version?

**Comment by totaam** [comment]
Not heard back and this works for me with up to date versions.
