### ISSUE TITLE
can not use client kebord input 

### ISSUE THREAD

**Issue by catcherxuefeng** [Xpra-org/xpra-html5#126]
i use Chinese input method 
on h5 webpage can use us-keyboard is work will 
but when I type in Chinese, there is no response
[imgs](https://s4.ax1x.com/2021/12/19/Te2Xan.gif)

**Comment by totaam** [comment]
I don't understand. What is `h5 webpage`?
What application are you running? What OS? What versions? etc..

**Comment by totaam** [comment]
Not enough information provided.
