### ISSUE TITLE
HTML5 client on HIDPI screens

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra-html5#13]
*Issue migrated from trac ticket # 2410*

**component:** html5 | **priority:** minor

#### 2019-09-09 14:48:39: sali.andrew created the issue

___
> Hi,
> 
> I wanted to ask if there are plans to support HiDPI (e.g. Retina) screens for HTML 5 clients. Out of the box the HTML 5 client will use the css width / height properties to render the server screen, which will result in relatively low resolution displays (the virtualized screen resolution is small).
> 
> With some small changes we managed to get around this by using the window.devicePixelRatio to render a higher res screen on the server and scale it back via css transform to the original screen (plus some small changes on the mouse handling). After this the screens look nice and sharp on Retina displays as well.
> 
> Would such a patch be considered for inclusion in the repository? Many screens these days tend to have HIDPI resolutions, so some kind of better support might be welcomed by the community.
> 
> Many thanks for your great work on this project,
> 
> Regards,
> 
> Andras
> 
>

**Comment by ShadowJonathan** [comment]
I'm encountering this issue after switching to xpra-html5 (as the macos version just had too many bugs), where the canvas on my scaled display becomes fuzzy.

**Comment by totaam** [comment]
> as the macos version just had too many bugs

@ShadowJonathan  What specific bugs?
Those are more likely to get fixed than an `xpra-html5` issue that I cannot test for lack of hardware.

**Comment by ShadowJonathan** [comment]
> What specific bugs?

I'll have to get back to you on that at a later point, i'll make a todo item to file them.

**Comment by totaam** [comment]
Not heard back.

**Comment by ShadowJonathan** [comment]
Apologies, though I haven't encountered this bug again on html5, though macOS native scaling was off/odd since a second ago.
