### ISSUE TITLE
Keyboard pop up in mobile chrome and safari.

### ISSUE THREAD

**Issue by Vssblt** [Xpra-org/xpra-html5#147]
Bugs: 

Keyboard pop up in mobile chrome and safari when touched canvas.

Add `readonly` to pasteboard textarea will fix this bug.

**Comment by totaam** [comment]
That would also prevent us from setting the clipboard, wouldn't it?

**Comment by Vssblt** [comment]
Clipboard works fine.
[There is video add readonly attribute.](https://vssblt.com/2.webm)

**Comment by totaam** [comment]
@Vssblt does the commit above fix things?

**Comment by Vssblt** [comment]
Yes, it works fine on my phone.
