### ISSUE TITLE
default-settings.txt missing on Ubuntu-20.04

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra-html5#149]
Hi,

I noticed that the `default-settings.txt` file is missing on Ubuntu-20.04 official deb package because it creates a symlink to a location that does not have the file:

```
root@xpra-server-:/usr/share/xpra/www# ls -la default-settings.txt 
lrwxrwxrwx 1 root root 43 Dec 19 05:31 default-settings.txt -> /etc/xpra/html5-client/default-settings.txt
```
```
root@xpra-server:/usr/share/xpra/www# ls -la /etc/xpra/html5-client/default-settings.txt
ls: cannot access '/etc/xpra/html5-client/default-settings.txt': No such file or directory
```
Copy paste and such never worked for me, so I wonder if this is linked to this. I specified the options in xpra.conf, but I guess this wasn't the right place to do so.

Thanks

**Comment by totaam** [comment]
@basilgello ?

**Comment by basilgello** [comment]
@iDmple by official deb package you mean one in Xpra repo or in Ubuntu repo hosted by Canonical?

**Comment by totaam** [comment]
@basilgello I assume the xpra repo since he reported here.

**Comment by basilgello** [comment]
@totaam OK let me run a test build for Ubuntu and check what is broken.

**Comment by iDmple** [comment]
Hey, sorry yes the Xpra repo!

**Comment by totaam** [comment]
@iDmple please try the latest packages from the beta channel, those have the correct symlinks in place.

**Comment by iDmple** [comment]
Thanks for the fix! Will do.

**Comment by iDmple** [comment]
I can confirm the bug is fixed on the beta channel!
