### ISSUE TITLE
Ios problems

### ISSUE THREAD

**Issue by ThrawnJL** [Xpra-org/xpra-html5#155]
Hi

Hopefully I am in the right place, if not my appologies.

I am trying to get "Filebot-xpra" to run on my ios devices (iphone and ipad running latest ios versions) 

Developer send me here because it seems that its the XPRA part I have issues with.

When I try and load the website on any of my IOS devices It shows "connecting to server" then my ip and port and then a load line that does nothing.

on a pc with edge browser (chrome version) it works fine.

Anything I can do to get this to work?

**Comment by totaam** [comment]
There is nowhere near enough information to be able to even begin looking into this.
Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by ThrawnJL** [comment]
> I can try as much as possible. Again I am trying to get another piece of software working thats appararently using XPRA a lot of it i dont know how to get 🈂️ 

_**what operating system is used on both the client and server, including the full version details**_
as for the server I am using docker 20.10.3-1233 on a Synology 1821+ NAS running DSM 7.0.1-42218 update 2
The clients are running. IOS 15.3.1 both on ipad and iphone


**_the network setup, bandwidth constraints (ie: local, LAN or DSL_**
LAN 1gbit via managed switch to server, wifi on clients

**_the full command lines used both on the server and client_**

Dont know how 

_**the server log file, or output if no log file is used**_
Still dont know how. The docker logs shows noting unusual. It shows nothing at all when trying to connect via IOS

**_is it reproducible reliably? and if so, how?_**
Try and login via ios device 

**_does it happen with other type of clients (different OS, etc)_**
Just IOS it works in windows using edge browser



Is there something specific I can ask the filebot developer about? 

All I see is the docker container and the result on ios that is shown on the attached picture
![272865171_678144826562402_3710079426169319315_n (1)](https://user-images.githubusercontent.com/87524390/154796443-ae295273-98e9-444a-8c23-41b88f710a19.jpg)

**Comment by rednoah** [comment]
Test Case:

1. Run docker container with Xpra server inside:
```
docker run --rm -it -v $PWD:/volume1 -v data:/data -p 5454:5454 rednoah/filebot:xpra
```
2. Open Xpra HTML5 client on iOS device and check if it can connect:
```
http://localhost:5454/
```


I got some console output via the Safari developer tools and it seems to just not load some JS files due to some CSP rule:
![Screen Shot 2022-02-19 at 23 00 08](https://user-images.githubusercontent.com/1589068/154808627-5ad0a32d-ce0f-4884-907a-b22645cd2541.png)
![Screen Shot 2022-02-19 at 22 57 15](https://user-images.githubusercontent.com/1589068/154808633-f4755027-dc89-4a95-9bf6-69fc2349e1e4.png)

**Comment by totaam** [comment]
> the full command lines used both on the server and client

Ask `filebot-xpra`?

> I got some console output via the Safari developer tools...

Please use don't use images for text data. Cut & paste it instead.

My guess is that you're running an outdated version without this fix: https://github.com/Xpra-org/xpra/issues/3422

**Comment by rednoah** [comment]
Thanks! Just a matter of rebuilding the docker container if the fix has already been released then. 🙏
