### ISSUE TITLE
Unclear operator precedence.

### ISSUE THREAD

**Issue by mdavidsaver** [Xpra-org/xpra-html5#161]
https://github.com/Xpra-org/xpra-html5/blob/a404158e945be6c1066f468c4f5e05e24b4d9641/setup.py#L552

Something I noticed while reading through `setup.py`.  May not cause any problem, but it may not function as I suspect was intended.

```py
if ( sys.platform.startswith("win") or sys.platform.startswith("darwin") ) and len(args)==3: 
```

Though I think operator precedence means this will be interpreted as:

```py
if sys.platform.startswith("win") or ( sys.platform.startswith("darwin") and len(args)==3 ):
```

**Comment by totaam** [comment]
You're right, that was wrong:
```
> True or False and False
True
```

Thanks for the report!
