### ISSUE TITLE
Source for the icons?

### ISSUE THREAD

**Issue by thkoch2001** [Xpra-org/xpra-html5#166]
I'm currently going through the debian/copyright file for a Debian package of xpra-html5 and wonder what the copyright and license of the icons might be. I assume you have not drawn them yourself and e.g. the speaker icon looks familiar.

Do you remember where you took the icons from? Are they all from the same icon-set?

**Comment by totaam** [comment]
Sorry, no idea.
Some of them were actually drawn by someone else, others just modified from one of the open-source sets.
