### ISSUE TITLE
xpra.org/src has only 4.5.1, github has 4.5.2

### ISSUE THREAD

**Issue by thkoch2001** [Xpra-org/xpra-html5#167]
https://xpra.org/src has only [xpra-html5-4.5.1.tar.xz](https://xpra.org/src/xpra-html5-4.5.1.tar.xz).
Github has [4.5.2](https://github.com/Xpra-org/xpra-html5/releases/tag/v4.5.2)

Is this intended?

**Comment by totaam** [comment]
Ooops! Fixed.
