### ISSUE TITLE
Question(s) about 'default-settings.txt' setup in 'setup.py'.

### ISSUE THREAD

**Issue by sbradnick** [Xpra-org/xpra-html5#168]
Attempting to switch OBS to using 'latest git' for both `xpra` & `xpra-html5` and I'm having issues with the build process complaining about how the setup for `default-settings.txt` symlink is being done (not that it's bad coding or anything, but maybe _more_ differences in how openSUSE does a few things).

With no changes to `setup.py`, I get a complaint near the end where it says:

```
[  171s] ERROR: link target doesn't exist (neither in build root nor in installed system):
[  171s]   /usr/share/xpra/www/usr/share/xpra/www/default-settings.txt -> /etc/xpra/html5-client/default-settings.txt
```

The oddest part is the duplication of `/usr/share/xpra/www` in the symlink it's trying to create.

A diff like so, makes the build process complete (and I'm not noticing any deficiencies, but that might just be how I've been using it); granted I don't have an `/etc/xpra/html5-client` directory or `/etc/xpra/html5-client/default-settings.txt` symlink but I'm sure a `%post` could take care of that.

```diff
diff xpra-html5-git20220322.82199bc/setup.py /tmp/xpra-html5/setup.py 
260,261c260,261
<                 #os.symlink(config_file, dst)
<                 print("config file NOT symlinked: %s -> %s" % (dst, config_file))
---
>                 os.symlink(config_file, dst)
>                 print("config file symlinked: %s -> %s" % (dst, config_file))
542,543c542
<         #install_dir = os.path.normpath(os.path.join(sys.prefix, "share/xpra/www"))
<         install_dir = ""
---
>         install_dir = os.path.normpath(os.path.join(sys.prefix, "share/xpra/www"))
```

**Comment by sbradnick** [comment]
It also seems to possibly be combining `install_dir` and `config_dir`:

(I can't completely confirm if the OBS `.spec` file is [indirectly] doing this or it's part of what `setup.py` does.)

```
$ rpm -ql xpra-html5 |  grep html5-client
/usr/share/xpra/www/etc/xpra/html5-client
/usr/share/xpra/www/etc/xpra/html5-client/default-settings.txt
```

It's being called via `PATH=$PATH:../package/bin python3 setup.py install %{buildroot}%{_datadir}/%{name}/www` ...

If I remove `%{buildroot}%{_datadir}/%{name}/www` and put `install_dir` back to default it just errors out because it isn't/won't work on the NON `%{buildroot}` instance.

**Comment by totaam** [comment]
Once again, this breakage is caused by #112.

> It's being called via `PATH=$PATH:../package/bin python3 setup.py install %{buildroot}%{_datadir}/%{name}/www ...`

Please try:
```
PATH=$PATH:../package/bin python3 setup.py install      %{buildroot}     %{_datadir}/%{name}/www ...
```
The first argument is the buildroot, now separated from the other arguments so that the installer knows not to include it in the symlinks it generates: the links may be broken when the filesystem layout is generated but they will actually point to the right place once installed outside the buildroot.
The alternative would be to use relative symlinks - but there's bound to be other problems with that too.

> EDIT: I also think it might be time to separate out `xpra` and `xpra-html5` into 2 distinct .spec files in OBS.

Absolutely, the two projects are now completely separate and evolve at different paces.

**Comment by sbradnick** [comment]
How about that, a simple space fixed it - excellent! - thanks for the help. I think I had that thought looking @ `install_dir` & `config_dir`, but there are times where I don't want to assume I see something different from what the existing `.spec` (in OBS) is doing and change too much.

Currently OBS is building both as part of a single `.spec` and it is kinda fussy as well as seemingly not working well with some convenience helpers (esp. for getting git sources); so I'm going to work next on getting them separated out.
