### ISSUE TITLE
Disable url forwarding 

### ISSUE THREAD

**Issue by tou2** [Xpra-org/xpra-html5#169]
I am having an issue when I click on hyperlinks in some programs it opens the link in the main browser not the browser inside xpra ubuntu.

Is this a feature I can disable?

**Comment by totaam** [comment]
```shell
$ xpra -h | grep -A1 url
    --open-url=yes|no|ask
                        Automatically open URL (potentially dangerous).
```

**Comment by tou2** [comment]
Thank you very much. 
I should read the man page more carefully next time.
