### ISSUE TITLE
🎉🎉🎉 Xpra-html5-vue

### ISSUE THREAD

**Issue by fungaren** [Xpra-org/xpra-html5#170]
Hello everyone, about one month ago, I was (almost completely) rewriting xpra-html5 (master branch) based on Vue.js (v3) and Webpack5. This means many front-end developers can reuse xpra-html5 as a part of their complex large system (this is the major reason for me to do such a complicated work), and bring us lots of benefits.

- Modern Javascript syntax
- Modern browser function (WebCodecs, Media Source Extensions, OffscreenCanvas, ...)
- Never reinventing the wheel
- Easily comprehensible
- Easily maintaining and extending
- Easily integrated with other system

Many features like window-management (dragging, resizing, hide/restore, ...), start-menu, (virutal) keyboard, clipboard sharing, ... are also supported.

My work is based on commit [82199bc802571876f0b0ed20bc7e8dcce5257d02](https://github.com/Xpra-org/xpra-html5/commit/82199bc802571876f0b0ed20bc7e8dcce5257d02). On the same time, I have found some bugs (maybe already fixed or not):

- Unable to fetch clipboard data from server (but pushing is good)
- Unable to type accents (éèêëẽ)
- Unable to use IME (Input Method)
- Unable to copy-cut-paste non-ascii characters (maybe caused by the encoding method)

![2022-04-27 19-29-00 的屏幕截图](https://user-images.githubusercontent.com/8206464/165508636-07ff6b0a-83b3-4189-b86f-93d49e677610.png)

![2022-04-27 19-28-21 的屏幕截图](https://user-images.githubusercontent.com/8206464/165508665-a93d4f42-c82e-45d8-a5fd-2889a1f3652b.png)

![2022-04-27 19-42-31 的屏幕截图](https://user-images.githubusercontent.com/8206464/165510886-2f7d5669-d4ab-4b9a-b189-5344b2ec253f.png)

I will make my work open-sourced in next days (very soon, maybe tomorrow) with the same license (MPL-2.0). I hope this work can be accepted by Xpra.org and keep maintained by the community. Thanks Xpra, and every contributor.

**Comment by nocbtm** [comment]
np

**Comment by totaam** [comment]
You may want to come and discuss this on this channel: https://discord.com/channels/934131122504343572/939997428696883260

When submitting PRs, please make sure to split the changes in digestible chunks.

**Comment by fungaren** [comment]
@totaam Seems that I have no permission to access the channel. And I don't think submitting PRs is a good idea because the whole structure of the project have been changed, and most files have been 100% rewritten. I have created a new repository, and further discussion is welcomed.

https://github.com/fungaren/xpra-html5-vue

**Comment by JanCVanB** [comment]
This is cool, @fungaren! Here's an invite link to that Discord server, where we discuss various web client works-in-progress: https://discord.gg/SzPxUbqmgD
