### ISSUE TITLE
Why is the `XpraProtocol.process_receive_queue()` loop empty?

### ISSUE THREAD

**Issue by JanCVanB** [Xpra-org/xpra-html5#179]
https://github.com/Xpra-org/xpra-html5/blob/ace424d66907668bd74a04f6737ffaa5dfa42e06/html5/js/Protocol.js#L226-L229

Should we delete this method, or should we fill the loop with something?

**Comment by totaam** [comment]
Because `do_process_receive_queue` will return `true` until all the packets in the queue have been processed.
I admit that this isn't the easiest code to read, linters may well complain about it too, the alternatives just take up more space.

**Comment by JanCVanB** [comment]
Ah, now I understand, thank you. I might propose a more linter-approved pattern, and then we can decide if it's an improvement.
