### ISSUE TITLE
Identical `XpraClient` methods

### ISSUE THREAD

**Issue by JanCVanB** [Xpra-org/xpra-html5#187]
What is the difference between [`XpraClient._process_window_move_resize()`](https://github.com/Xpra-org/xpra-html5/blob/59a8f90bb7264f83b9be10e985846feab5848794/html5/js/Client.js#L3597) and [`XpraClient._process_configure_override_redirect()`](https://github.com/Xpra-org/xpra-html5/blob/59a8f90bb7264f83b9be10e985846feab5848794/html5/js/Client.js#L3609)?

https://github.com/Xpra-org/xpra-html5/blob/59a8f90bb7264f83b9be10e985846feab5848794/html5/js/Client.js#L3597-L3607
https://github.com/Xpra-org/xpra-html5/blob/59a8f90bb7264f83b9be10e985846feab5848794/html5/js/Client.js#L3609-L3619

Is one a mistake? Should they merge?

**Comment by JanCVanB** [comment]
They're both used once.

**Comment by andersevenrud** [comment]
Aside from the "packet name", they both have the same data.

A nice way to clean this up without having to wrap it etc. would be:

```js
const [, wid, x, y, width, height] = packet
const win = this.id_to_window[wid]; 
if (win != null) win.move_resize(x, y, width, height);

// This is even nicer if you don't care about IE :D
win?.move_resize(x, y, width, height);
```

**Comment by JanCVanB** [comment]
> Aside from the "packet name", they both have the same data.
> 
> A nice way to clean this up without having to wrap it etc. would be:
> 
> ```js
> const [, wid, x, y, width, height] = packet
> const win = this.id_to_window[wid]; 
> if (win != null) win.move_resize(x, y, width, height);
> 
> // This is even nicer if you don't care about legacy :D (can be polyfilled or transpiled)
> win?.move_resize(x, y, width, height);
> ```

```js
  _process_foo(packet) {
    const [, wid, x, y, width, height] = packet;
    this.id_to_window[wid]?.move_resize(x, y, width, height);
  } 
```
 Beautiful.

**Comment by JanCVanB** [comment]
I'd still like to de-duplicate/merge them, though!

**Comment by andersevenrud** [comment]
> I'd still like to de-duplicate/merge them, though!

Personally I don't really see any value in this when it can be boiled down to a couple of lines. It introduces a little bit of mental overhead, especially when it comes to debugging (and unit tests if that comes down the road).

**Comment by JanCVanB** [comment]
Good point. I'd still like to confirm that these functions are named and implemented correctly, though!

**Comment by andersevenrud** [comment]
> I'd still like to confirm that these functions are named and implemented correctly, though!

As to my understanding they're named correctly and provides the correct behavior in this context. The "override redirect" here would be something like a context menu or popup, that behaves like a window, but without certain decorations etc. that have distinct packets.

**Comment by JanCVanB** [comment]
That's great! I'll see if the new linting rules allow the shortened functions to stay duplicates.

**Comment by JanCVanB** [comment]
[The linter rule in question](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/no-identical-functions.md) doesn't mind duplicates if they're short! 🎉

**Comment by totaam** [comment]
These methods are slightly different in the Python client which handles window synchronization issues with non OR windows (the `resize_counter` feature).
The html5 client does not, so the implementation is the same there.
