### ISSUE TITLE
Instructions for manual installation are erroneous

### ISSUE THREAD

**Issue by slavistan** [Xpra-org/xpra-html5#190]
Hi there! I've just managed to get xprop running and connect to it from the browser on another machine using the `xpra-html5` webserver. I've noticed a small error in either the README or, depending on how you put it, in the `setup.py` file:

The installation instructions tell one to run `./setup.py install /usr/share/xpra/www`, which erroneously produces the following directory structure:

```
pi@raspberrypi:~ $ tree -L 4 /usr/share/xpra/www
/usr/share/xpra/www
├── etc
│   └── xpra
│       └── html5-client
│           └── default-settings.txt
└── usr
    └── share
        └── xpra
            └── www
```
This way the `xpra` webserver does not work, as it tries to pick up html files inside */usr/share/xpra/www*, where there are none. Instead they are located at */usr/share/xpra/www/usr/share/xpra/www*. It looks as if the default prefix is used in addition to the user's custom prefix, as well as being applied to the *default-settings.txt* configuration file's path. This error exists for v4.* and v5.0.

Given all this the easiest quickfix is to install the webserver using `./setup.py install` and it will just work.

Thanks a ton for your great work!

**Comment by totaam** [comment]
Thanks for reporting this, the two commits above fix the examples and default instructions.
