### ISSUE TITLE
Roadmap -- future of the HTML5 Client

### ISSUE THREAD

**Issue by knackstedt** [Xpra-org/xpra-html5#208]
Are there any plans on building support for embedding singular apps in websites -- and are there any plans on potentially rewriting HTML5 client in React or Angular?

**Comment by totaam** [comment]
@knackstedt as per above, this is better discussed on discord or through https://github.com/Xpra-org/xpra-html5/discussions
I am closing this ticket as there is no specific "issue" to work on.
