### ISSUE TITLE
Configure apache to span xpra session.

### ISSUE THREAD

**Issue by neroita** [Xpra-org/xpra-html5#209]
Hi all,
is there a way to configure apache to span a xpra session every time anyone visit a url ?
I'm trying to publish a linux app for everyone , I can use apache to proxy xpra but:
* I need to start xpra before and choose app to run
* everyone see same session

Is possible to make apache span a new session of xpra everytime a user open the url ?

thanks in advance.

**Comment by totaam** [comment]
I'm sure there's much better ways of doing this, but the quick and dirty approach would be to write a custom CGI script that runs `xpra start` for each visit to your URL and assign a unique server ID within a given range, then you should be able to use some `ProxyPass` magic to map URLs to individual server ports. See:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Apache-Proxy.md

**Comment by neroita** [comment]
Uhmm , I've made a try but I have problem on timing and shutting down the sessions.

I've the same setup made with x2go but I would like to try xpra.

**Comment by totaam** [comment]
> Uhmm , I've made a try but I have problem on timing and shutting down the sessions.

Without seeing your code, it is impossible to help you.
> I've the same setup made with x2go but I would like to try xpra.

I don't see why it would be any harder.
