### ISSUE TITLE
unable to move any window

### ISSUE THREAD

**Issue by mkresin** [Xpra-org/xpra-html5#210]
Using the v6 branch or master, I'm not able to move any window.

I used the latest packages provided for ubuntu 20.04 "jammy", which are xpra 4.4.1-r35-1 and xpra-html5 6.0-r1-1. For further testing I used a git clone of the html5 repository:

`/usr/bin/xpra --daemon=no --bind-ws=0.0.0.0:8080 --html=/home/mkresin/build/xpra-html5/html5/ --start-child-after-connect=/usr/bin/gedit start :100`

Tested browser are Google Chrome 107.0.5304.87 and Firefox 106.0.2.

Git bisect tells me that ced316f4833d80f80d238aa7252628f18d2faed8 introduced the regression for me. Applying the following change fixes the issue for me:

```diff
--- a/html5/js/Window.js
+++ b/html5/js/Window.js
@@ -329,9 +329,15 @@ class XpraWindow {
 
   register_canvas_mouse_events(canvas) {
     // Hook up the events we want to receive:
-    jQuery(canvas).mousedown((e) => this.on_mousedown(e));
-    jQuery(canvas).mouseup((e) => this.on_mouseup(e));
-    jQuery(canvas).mousemove((e) => this.on_mousemove(e));
+    jQuery(canvas).mousedown((e) => {
+           this.on_mousedown(e)
+    });
+    jQuery(canvas).mouseup((e) => {
+           this.on_mouseup(e)
+    });
+    jQuery(canvas).mousemove((e) => {
+           this.on_mousemove(e)
+    });
   }
 
   register_canvas_pointer_events(canvas) {
```

To be honest, I've no idea what the curly brackets change here.

Also, I'm a little surprised that I'm apparently the only one noticing the problem after >5 months. Still not sure, if there might be something wrong on my side.

**Comment by totaam** [comment]
@mkresin we've had two releases (v5 and v6) since that arrow function change - I would have expected one of us to see this problem!
Do you have anything in your javascript log?

**Comment by mkresin** [comment]
> we've had two releases (v5 and v6) since that arrow function change

The change is not present in the v5.x branch (https://github.com/Xpra-org/xpra-html5/blob/v5.x/html5/js/Window.js#L293) and the v5.x branch doesn't show the issue for me.

> Do you have anything in your javascript log?

Nope, no error or obvious warnings. That was the first place to check prior to starting the bisect.

I went ahead and setup a new ubuntu 20.04 virtual machine. After performing the following steps, the issue shows up as well:

0. install all available updates
1. install vim, git, openssh-server (likely unrelated)
2. add xpra.org apt sources
3. `apt install xpra xpra-html5` (xpra 4.1.4, xpra-html5 6.0)
4. run as user `xpra --daemon=no --bind-ws=127.0.0.1:8080 --start-child-after-connect=/usr/bin/gedit start :100`
5. open browser within virtual machine and navigate to `http://127.0.0.1:8080`

**Comment by totaam** [comment]
> try to move the gedit window

Wait, so it's not just any window, right?
It's a special "initiate-move-resize" window. Have you tried with an xterm?

**Comment by mkresin** [comment]
Indeed, moving xterm or thunderbird works.

Not working is moving of the window of file manager, editor, disk usage analyser and so on.

**Comment by totaam** [comment]
Those are all applications without a window frame or that don't use the OS window frame and draw their own.
They rely on "initiate-move-resize" to be moved and that was broken.
I've applied your fix, even though I don't really understand why that would change the event callback scope..
