### ISSUE TITLE
Missing mouse Scroll events in v4.3.3

### ISSUE THREAD

**Issue by raymondpau** [Xpra-org/xpra-html5#223]
No mouse scroll event received when starting xpra with "start-desktop".
3 buttons mouse correctly detected.
Scroll wheel button click event received correct using xev.
But no event received when scrolling the wheel.
Same configuration works for XPRA v3.1-build5 but not with XPRA v4.3.3

**To Reproduce**
1.
```
xpra start-desktop :1 --bind-tcp=0.0.0.0:8080 --mdns=no --webcam=no --pulseaudio=no \
    --start="xhost +" --xvfb='xinit +fullscreen  -- :1 ' --tray=no --system-tray=no \
    --video-encoders=nvenc --printing=no --resize-display=1920x1080
```
3. `kubectl port-forward <svc/service-name> 8080`
4. Access client using `http://localhost:8080/`
5. Open a terminate to server and execute `xev`
6. Scroll mouse wheel with pointer inside xev client window
7. mouse scroll events expected in console but missing with XPRA v4.3.3 with xpra start-desktop

**System Information (please complete the following information):**
 - Server OS: ubuntu:22.04 (running on Azure aks)
 - Client OS: MacOS Ventura 13.1
 - Browser: Google Chrome Version 109.0.5414.119 (Official Build) (x86_64)
 - Xpra Server Version 4.3.3
 - Xpra Client Version 4.3.3 - using html5-client that comes with xpra v4.3.3

**Additional context**
With xpra start, mouse wheel scroll events correctly received by xev.

xpra start mouse wheel logs:
```
2023-02-07 08:04:07,701 do_process_mouse_common(WebSocket(ws socket: 127.0.0.1:8080 <- 127.0.0.1:60108), 0, (1430, 1071), -1)2023-02-07 08:04:07,702 <bound method XTestPointerDevice.click of XTestPointerDevice>(4, True, ())2023-02-07 08:04:07,702 xtest_fake_button(4, True)
2023-02-07 08:04:07,702 process_button_action(WebSocket(ws socket: 127.0.0.1:8080 <- 127.0.0.1:60108), ['button-action', 0, 4, False, (1430, 1071), (), ()])
```

xpra start-desktop mouse wheel logs:
```
2023-02-07 08:05:20,592 process_button_action(WebSocket(ws socket: 127.0.0.1:8080 <- 127.0.0.1:60610), ['button-action', 0, 4, False, (1517, 926), (), ()])
```
[xpra-4.3.3-bug-report.zip](https://github.com/Xpra-org/xpra/files/10703447/xpra-4.3.3-bug-report.zip)

**Comment by raymondpau** [comment]
As per your recommendation, I tried using a simpler command to isolate the problem.

xpra start :1 --bind-tcp=0.0.0.0:8080 --start="xterm"
Mouse scroll wheel events correctly received with this command.

xpra start-desktop :1 --bind-tcp=0.0.0.0:8080 --start="xterm"
The only difference is changing from start -> start-desktop; with this mouse scroll events are not received.

**Comment by totaam** [comment]
> Edit: moved to html5 client since the bug occurs only with this client.

I have isolated the problem and will try to get a fix out soon.
The html5 client sends the scroll events without specifying the "window". In desktop mode, there is usually just one "window" representing the whole desktop.

**Comment by raymondpau** [comment]
I was about to send you some python debug information as follows:
-> self.do_process_button_action(proto, *packet[1:])
(Pdb) a
self = <desktop_server.XpraDesktopServer object at 0x7f57ed0b8380 (xpra+x11+desktop+desktop_server+XpraDesktopServer at 0x55c3dd496740)>
proto = WebSocket(ws socket: 127.0.0.1:8080 <- 127.0.0.1:36128)
packet = ['button-action', 0, 4, True, (122, 102), (), ()]

Which shows the windows id as 0 as you explained.

**Comment by totaam** [comment]
> Which shows the windows id as 0 as you explained.

Yes,  the problem comes from the html5 client - which is why I moved the ticket to this repository.

**Comment by totaam** [comment]
@raymondpau the commit above should fix things.
Works-for-me(tm).

**Comment by raymondpau** [comment]
When will a official release be available? Tried updating only the file with your changes onto xpra v4.4.3. Wheel Scroll works but the screen freezes after some mouse clicking and dragging to move around. Going to try replacing the entire "www" folder with the master branch to see if will work better - but not sure how stable it is since it is still in beta.

**Comment by totaam** [comment]
> When will a official release be available?

When it is ready, I am hoping this will only take a few more days.

> Tried updating only the file with your changes onto xpra v4.4.3.

That doesn't make sense.
`4.4.3` is an xpra version, the fix is in the `xpra-html5` project, which uses a different version number, currently 7.x is the development version.

> Wheel Scroll works but the screen freezes after some mouse clicking and dragging to move around

Sounds like: https://github.com/Xpra-org/xpra-html5/issues/217#issuecomment-1423838313
(also fixed in git master)

> but not sure how stable it is since it is still in beta

Seeing that I intend to make a release in just a few days, it should be in good shape, I hope.
