### ISSUE TITLE
mitm.html Not found, Version >=6.x

### ISSUE THREAD

**Issue by CH-Evgeny** [Xpra-org/xpra-html5#225]
I am deploying an app to the path domain.com/example/userid

If I try to download a large file, I get an error that mitm.html can not be found.

Why did you overwrite a default path to the mitm.html in Client.js?  

```
 try {
      //try to use a stream saver:
      this.debug("file", "streamSaver=", streamSaver);
      streamSaver.mitm = "../mitm.html";
      const fileStream = streamSaver.createWriteStream(basefilename, {
        size: filesize,
      });
      writer = fileStream.getWriter();
      this.debug("file", "stream writer=", writer);
    }
```

**With default value it works.**

**Comment by totaam** [comment]
> With default value it works.

If you mean the URL `https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=2.0.0`, then no, we can't use that if we want to keep the client self-contained.

Relative URLs do work when deployed with the xpra server, so I don't see why it would not work with subdirectories.
Is there anything else that you're changing?

**Comment by CH-Evgeny** [comment]
I do not quite understand how this path relates to the xpra server, but the application is deployed with the xpra server.
Nothing else has been changed.

Why doesn't this work with self-contained client? mitm.html is in the same directory as index.html of xpra Client. 

`streamSaver.mitm = "./mitm.html";` or just `streamSaver.mitm = "mitm.html";` should work, right?

**Comment by totaam** [comment]
> the application is deployed with the xpra server.
> Nothing else has been changed.

Then why did you say:
> I am deploying an app to the path domain.com/example/userid

Isn't this relevant? Isn't there some kind of proxying going on here?
This relative path was added in ce0bc83c72e628030eab248a07134f20862397fb for #120.
I have no idea if the path is going to be relative to `index.html` or `./js/Client.js`.
Are you saying that using `streamSaver.mitm = "./mitm.html";` is a fix?
If so, try 953523e66c1a2e16d9ae1d4c67e070f0e95f9ad6.

**Comment by CH-Evgeny** [comment]
yes, I use proxy. 

domain.com/example/userid is just URL, there are no such subdirectory on the server with xpra Client. 

yes, it works if the path is going to be relative to index.html and "./mitm.html" is the default value set in SreamSaver.js 
I think you can just remove this line from Client.js

**Comment by totaam** [comment]
> If so, try 953523e66c1a2e16d9ae1d4c67e070f0e95f9ad6

Did that work then?

**Comment by CH-Evgeny** [comment]
yes, it did

**Comment by totaam** [comment]
Thanks.
This fix will be included in the next release.
