### ISSUE TITLE
safari doesn't draw the window - only a hollow transparent shell

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra-html5#227]
It's almost impossible to bisect because it occasionally displays correctly!
Disabling the offscreen decode worker and even the decode worker does not help.
I think that the decoding part works, it is the `draw_pending_list` that's not doing its thing?

**Comment by TijZwa** [comment]
Let me see if I can find my macbook :) and investigate this.

**Comment by TijZwa** [comment]
I've tested witj Safari 15.6.1 on macOS 12.6.3 and it works with both SSL and non-SSL context.
Do I miss something?

![image](https://user-images.githubusercontent.com/19667394/220457798-a6d02f94-8d7b-4961-b5e2-fa4eb0c54ba0.png)
![image](https://user-images.githubusercontent.com/19667394/220457919-984827c3-b05b-4981-9dea-212941815189.png)

**Comment by totaam** [comment]
Well, that's interesting. It means that perhaps https://github.com/Xpra-org/xpra/issues/3769 is also a false positive.
Either a problem with VirtualBox or Apple's software OpenGL driver.

Do you have a newer MacOS to test with?
Can you try the latest MacOS beta with `--opengl=force`?

**Comment by heinosasshallik** [comment]
I don't think it's a problem with VirtualBox, since I believe I was able to replicate this on a physical Macbook. I applied the workaround mentioned in https://github.com/Xpra-org/xpra-html5/issues/226, but instead of xpra drawing my application, I just got an empty window.

**Comment by totaam** [comment]
I modified the `draw` function to just put some text on the canvas, then call the draw function after creating the window in various ways:
```javascript
win.draw("new window done");
window.requestAnimationFrame(function() {win.draw("new2");});
window.requestAnimationFrame(function() {win.draw("new3");});
setTimeout(function() {win.draw("new4");}, 100);
setTimeout(function() {window.requestAnimationFrame(function() {win.draw("new5");})}, 100);
```
And only the first 3 show up, nothing after that.
Safari is broken, use a better browser.

So I've already spent too much time on this and I have no idea what's broken with Safari.
Unless someone else takes a look at it, this won't be fixed. Use a better browser.
[Safari is the new Internet Explorer](https://www.safari-is-the-new-ie.com/)

**Comment by ojasookert** [comment]
@TijZwa could you share the builds/commits you had this working on?

**Comment by dexion** [comment]
<img width="615" alt="image" src="https://github.com/Xpra-org/xpra-html5/assets/177283/e2a620ec-eb76-4f04-a9c5-d3e4059711f0">

Client:
Safari 16.5
MacOS 13.4

Server:
The latest public xpra-4.4.5 from packages

**Comment by taradaidv** [comment]
> It's almost impossible to bisect because it occasionally displays correctly!
> Disabling the offscreen decode worker and even the decode worker does not help.
> I think that the decoding part works, it is the `draw_pending_list` that's not doing its thing?

<img width="613" alt="Screenshot 2023-06-10 at 21 22 02" src="https://github.com/Xpra-org/xpra-html5/assets/35196630/f84a13fb-5ad7-4fd5-a55c-83e3615cf0e5">

I'm also looking for what the problem is, there are a couple of sketches.
Now the easiest way is to disable **offscreen decoding**, but this is a crutch and not a solution

_tmp fix:_
echo -e "\noffscreen = false" >> /usr/share/xpra/www/default-settings.txt

**Comment by totaam** [comment]
> Now the easiest way is to disable offscreen decoding, but this is a crutch and not a solution

Last time I tried, that was not enough - at least with the Safari versions I had access to.

> `echo -e "\noffscreen = false" >> /usr/share/xpra/www/default-settings.txt`

That would disable offscreen for **all** browsers, including the ones that aren't buggy!
57d1c2aaefdcdb972a60a46f9b1526af45f588ac should disable it only for Safari.
Does that work for you?

**Comment by taradaidv** [comment]
Yep, that defines it well.
Now in Safari it disables offscreen and draws on the canvas, in other browsers offscreen works and draws too.

**Comment by totaam** [comment]
@taradaidv which versions of Safari have you tested?

**Comment by taradaidv** [comment]
latest
Safari on Mac
Version 16.5 (18615.2.9.11.4)

**Comment by jhgoebbert** [comment]
This bug-report might be of interest: https://bugs.webkit.org/show_bug.cgi?id=253927#c0
`This shouldn't happen often, but can happen if you draw to an OffscreenCanvas, call "commit()", and then draw again quickly (not waiting for rAF).`
A pull-request was merged in March but might not have been included in current Safari browsers, yet: https://github.com/WebKit/WebKit/pull/11534

**Comment by totaam** [comment]
Just discovered at the last minute that Google Chrome now requires https to enable offscreen: 52742e3f78fee5c098778f68094f7c58e603f22a
It doesn't complain, doesn't give any warnings, but doesn't paint the window either!
