### ISSUE TITLE
drop broadway decoder

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra-html5#228]
It's too slow.
Browsers can use offscreen decoding or live with `jpeg` / `webp` / `avif`.

**Comment by totaam** [comment]
@TijZwa do we want to re-instate the smoke test via the offscreen decode worker before enabling `h264` globally?

**Comment by TijZwa** [comment]
@totaam I think we already test:  [here ](https://github.com/Xpra-org/xpra-html5/blob/master/html5/js/OffscreenDecodeWorker.js#L35)and [here](https://github.com/Xpra-org/xpra-html5/blob/master/html5/js/VideoDecoder.js#L20)

The downside is that H264 will only work when the browser has the VideoDecoder API. 
See https://developer.mozilla.org/en-US/docs/Web/API/VideoDecoder#browser_compatibility

**Comment by totaam** [comment]
@TijZwa well, that's why I asked: those checks are not enough.
I had to add this line to have `h264` enabled:
https://github.com/Xpra-org/xpra-html5/blob/247f92e15eb6a3f65ed037e1e778772f26178d89/html5/js/Client.js#L517

Without it, `client.encodings` does not have `h264` in it and the server won't be sending it:
```shell
$ xpra info | grep client.encodings=
client.encodings=('jpeg', 'png', 'png/P', 'png/L', 'rgb', 'rgb32', 'rgb24', 'scroll', 'webp', 'void', 'avif', 'vp8')
```
