### ISSUE TITLE
Feature Request: add option to mirror mouse cursor when sharing

### ISSUE THREAD

**Issue by MarkoSchuetz** [Xpra-org/xpra-html5#229]
Scenario: a program is running on a laptop under xpra with `--sharing `.  From the laptop an instance of xpra attaches to the xpra server. From a tablet through xpra-html5 there is another attachment to that same server on the laptop. A mouse is connected to the laptop. Mouse movements from the laptop cannot be seen on the be tablet.

Target: a command-line option can be used when starting the server such that mouse movements from one client are propagated to all the other clients.

**Comment by totaam** [comment]
What type of session are you running? `shadow`, `seamless` or `desktop`?

**Comment by totaam** [comment]
Done in the xpra ticket above - works for both python clients and the html5 client by default.

This minor fix is useful for displaying cursors properly with the html5 client: 96132fa6791e1890b344ad910a190ad9cfd421b4

You haven't specified which distribution you are on, so it may be a while before your chosen distro hits the beta download area.
This will be included in the final `xpra` v5 release and `xpra-html5` v7.
