### ISSUE TITLE
v7.0 - "Reload" menu button causes windows to close

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#230]
The "Reload" menu button, which is meant to reconnect - sometimes causes windows to close.\
If the program prompts to confirm exit - after reloading, you will see that prompt. Other programs will be closed.

**Comment by totaam** [comment]
Please specify the exact versions and commands used.
Is this really specific to the html5 client or does it also occur with the python client?

**Comment by totaam** [comment]
So, these two commits had nothing to do with it:
* 2758d2d846db9138111f6220c98314f37c53f326 broke `close_window` by removing one argument
* 021d119cd4e6fe61eadc896a26847b4d62c9a9d2 fixed it
So between those two revisions, calls to `close_window` would not work and the bug would not trigger.

The fixes are in the 2 commits above.

Thanks for your patience!
