### ISSUE TITLE
Reconnecting is not working

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#233]
It is related to any version.

For example, if a system goes to sleep and then back - the client does not reconnect, hanging with a message "Connecting to server" indefinitely _(even though the option "Re-connect automatically" is enabled)._

![Screenshot 2023-03-17 10 22 07](https://user-images.githubusercontent.com/66574145/225932505-2883e24f-f738-45c9-964c-07e177390049.png)

**Comment by totaam** [comment]
> It is related to any version.

What specific version have you used for testing? What browser?
What OS?

What sort of connection is this?
Looks like `ssl` from the screenshot, but what is the server's command line?
Is this a tcp socket with ssl upgrades or an ssl socket?
What does the server log say?

**Comment by Rush-iam** [comment]
- client version - latest commit here
- OS - ChromeOS 112
- Browser - Chrome 112
- command: `xpra start --bind-ws=0.0.0.0:9999`
- server log gives only this line:
  `2023-04-03 14:49:28,974 websocket client 1 disconnected.` _(it is around the moment my laptop went to sleep)_

**Comment by totaam** [comment]
Is this fixed after #308 ?

**Comment by totaam** [comment]
Not heard back.

**Comment by Rush-iam** [comment]
Sorry, I am still stuck to Xpra 5.0.4 + client v12 because I am stuck with CUDA 11.
Will report back after upgrading to CUDA 12 next year.
