### ISSUE TITLE
Feature Request: Override Height

### ISSUE THREAD

**Issue by hazeltoh** [Xpra-org/xpra-html5#234]
Knowing that there is an option to override the width, would be great to have an option to override the height in addition to allow a static resolution size. 

Scenario: Using it with `start-desktop`, an application that do not cater for dynamic resizing will caused the screen to have empty spaces when launched if the resolution is larger than the resolution the application was launched in.

**Comment by totaam** [comment]
You may be able to achieve something similar by starting your server with `--resize-display=no` - I haven't checked.

I don't have the time to work on this feature, sorry.
