### ISSUE TITLE
Window closes on X-button even if it isn't closed because of the program prompt

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#235]
The window closes on X-button even if it isn't closed because of the program prompt.

For example, if you work on a file in a program and after clicking the X-button, the program asks you to save the file.
But the HTML client hides the program window from the user, making it look like the window was closed. To restore the hidden window, you need to reconnect.

This incorrect behaviour was introduced recently with the refactor of the Close button.

**Comment by totaam** [comment]
Thanks, fixed in the commit above.
