### ISSUE TITLE
New windows sometimes not on top

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#239]
When you launch a new program within the client, having a different window opened, the new one doesn't always get focused (doesn't go on top).

When some app opens an internal window (subwindow), the client may reshuffle window order  - the background window may become on top (or not on top but in the middle of three windows and return to the background after closing the top window).

**Comment by totaam** [comment]
Yes, window stacking should be completely re-written.
Unfortunately, I don't have time to dedicate to that.

**Comment by totaam** [comment]
Duplicate of #11
