### ISSUE TITLE
Can't connect through proxy when there are multiple Xpra sessions behind proxy

### ISSUE THREAD

**Issue by jacklovell** [Xpra-org/xpra-html5#243]
There is no way in connect.html to specify which Xpra session to connect to if connecting through a proxy. At the command line I can do:

```
xpra attach ssl://<username>@<server>:<tcp-port>/<display>
```
This connects to the Xpra server on `<display>` through the Xpra proxy which is listening on port `<tcp-port>`. But when connecting via the HTML client there is no way to distinguish between the TCP port and the server behind the proxy.

When only 1 server is running behind the proxy this isn't a problem as it's automatically selected when connecting to the proxy. But with more than one server I get redirected back to the connection page with the message:
```
You were disconnected for the following reason:
session not found error
```

I expect it'd be necessary to have an additional input specifying the display number when connecting via proxy. That could be a text (number) input box that's always there, or that only appears when the user selects a checkbox identifying they're connecting to a proxy sever. Or a third, more elegant solution I haven't yet thought of...

#### Steps to reproduce

Xpra version 3.1.4-r3M, server on Scientific Linux 7 (RHEL 7 clone).
Client Firefox 102 on MacOS 11.7.6.

```
xpra start :10000
xpra start :10001
xpra proxy :10002 --bind-tcp=0.0.0.0:10002  --html=on # plus tcp-auth, ssl, ssl-cert, ssl-key etc.
```
* Navigate to http(s)://<server>:10002 and put in 10002 as the port to connect to.
* Attempt to connect, get kicked out and observe the above error message.

**Comment by totaam** [comment]
The `display` form option is only shown when the html5 client is provided by a (recent enough) proxy server.

I believe that your problem would be solved by using a newer xpra server version and making sure that the html5 client is served by the builtin web server.
If you really want to be using an older server, you can try this:
```patch
diff --git a/html5/connect.html b/html5/connect.html
index 9b5a659..8da9342 100644
--- a/html5/connect.html
+++ b/html5/connect.html
@@ -1323,9 +1323,9 @@
 
         function show_mode(is_proxy) {
           Utilities.debug("show_mode(", is_proxy, ")");
+          $("#action_connect_group").show();
           if (is_proxy) {
             //show all options:
-            $("#action_connect_group").show();
             $("#action_start_group").show();
             $("#action_start_desktop_group").show();
             $("#action_shadow_group").show();
@@ -1337,7 +1337,6 @@
           } else {
             //only attach is possible, select it and hide everything:
             $("#action_connect").prop("checked", true);
-            $("#action_connect_group").hide();
             $("#action_start_group").hide();
             $("#action_start_desktop_group").hide();
             $("#action_shadow_group").hide();
```

**Comment by totaam** [comment]
Not heard back.
