### ISSUE TITLE
Closing the XHTML client page also closes my running application

### ISSUE THREAD

**Issue by anderslangballe** [Xpra-org/xpra-html5#245]
I'm using a setup in which I have:
1. Xpra running in a Docker container with the HTML5 client.
2. Firefox running in a separate Docker container, using the same X11 socket and display as the Xpra server.

The setup generally works fine, and I can interact with the browser through the HTML5 client as expected. 

However, I run into an issue when I disconnect or otherwise close the HTML5 client (running in my own browser). When closing, it sometimes also closes the Firefox browser. I'm unsure if this issue is specific to Xpra or this client, but I'd like the browser to stay open even if the client disconnects. 

In my Xpra configuration, I'm using the following settings:
```
exit-with-client=no
exit-with-children=no
```

**Comment by totaam** [comment]
I believe this is the same issue as #230 - please try the fix from there.

**Comment by anderslangballe** [comment]
Thanks for the quick response @totaam.

Indeed, that seems to solve my problem. Closing.
