### ISSUE TITLE
RegEx rejects spaces

### ISSUE THREAD

**Issue by taradaidv** [Xpra-org/xpra-html5#249]
https://github.com/Xpra-org/xpra-html5/blob/2add797f48fb5059a26bfdcb5e4ce24c6695caf0/html5/js/Client.js#L2969
<img width="508" alt="Screenshot 2023-05-24 at 13 36 07" src="https://github.com/Xpra-org/xpra-html5/assets/35196630/0fa6937f-7ed9-490b-b861-1f04ae4aff6a">

for fix need to add a space to the allowed characters
`/[^\d+,. /:a-z]/gi,`

**Comment by totaam** [comment]
Does the commit above do what you want? If so, please close the ticket.
FYI: you can also just edit the source file via github and submit a PR that way.

**Comment by taradaidv** [comment]
> Does the commit above do what you want? If so, please close the ticket.
> FYI: you can also just edit the source file via github and submit a PR that way.

yes, the fix does what i want.
next time I will try through PR thanks for the info
