### ISSUE TITLE
Black application form on first connection

### ISSUE THREAD

**Issue by CH-Evgeny** [Xpra-org/xpra-html5#251]
I run a dummy delphi application on ubuntu 22.04 with wine7 and xpra-server 4.4.4.
When connected for the first time with xpra-html5 client v.7, the application form is completely black. If I update or resize the browser window, then the application is displayed correctly

After first connection:
![Screenshot 2023-06-07 142426](https://github.com/Xpra-org/xpra-html5/assets/12543954/d4217843-175c-4ffd-8f45-78134b7b8d9b)

After update or resize: 
![Screenshot 2023-06-07 142533](https://github.com/Xpra-org/xpra-html5/assets/12543954/3444736c-c35d-4b69-812a-37fae4a1f778)

**Comment by CH-Evgeny** [comment]
the following message is in the log:
![image](https://github.com/Xpra-org/xpra-html5/assets/12543954/139bd8b1-e43d-40db-b848-f21e9014c9ff)

**Comment by CH-Evgeny** [comment]
ok. I could uplaod this dummy app to github. Can you compile it?

**Comment by CH-Evgeny** [comment]
I uploaded it to https://github.com/CH-Evgeny/testAppForXpraClient

**Comment by totaam** [comment]
> Given clear instructions

Still waiting.

**Comment by CH-Evgeny** [comment]
just compile the app, or take the Win32/Debug/Project1.exe from repository and start with command: 
`xpra start --start-child="wine Project1.exe " --bind-tcp=0.0.0.0:8085 --no-daemon`

**Comment by totaam** [comment]
> just compile the app

Yes, how?
