### ISSUE TITLE
Does the --speed / --min-speed still work?

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#266]
I worked with Xpra v4.3.4 and Client <8.1, and setting `--speed` affected refresh rate/quality significantly.

With Xpra 5.0.1+8.1, I tried both `--speed 1` and `--speed 100`, and they look/perform the same. Was it designed this way?

And I have confusion about the `--min-speed`/`--min-quality` options. Does it set the upper limit or the lower limit of the value? It is not clear from [the docs](https://xpra.org/manual.html).

**Comment by totaam** [comment]
> With Xpra 5.0.1+8.1, I tried both `--speed 1` and `--speed 100`, and they look/perform the same

As per `xpra --help`, these options only specify the default when used server-side.
The client can override the values and the html5 client now does:
https://github.com/Xpra-org/xpra-html5/commit/f133a43c35f797e7a5601ee3e3c348d6de6ee146#r126114207

This was a mistake as the correct place should be here instead:
https://github.com/Xpra-org/xpra-html5/blob/master/html5/default-settings.txt
(as this can be modified much more easily)

**Comment by Rush-iam** [comment]
> The client can override the values and the html5 client now does:

But this change is related to Xpra HTML 9.0+, and I am using 8.1 and still can't see any difference...
If Xpra 9.0 overrides `min-speed`, can I specify `--speed` on the server side to disable that overriding?

> --min-speed=SPEED   Sets the minimum encoding speed allowed in automatic speed setting,from 1 to 100, 0 to leave unset.        
> --speed=SPEED       Use image compression with the given encoding speed, from 1 to 100, 0 to use automatic setting. Default: 0.

**Comment by totaam** [comment]
> can I specify --speed on the server side to disable that overriding?

No, as per `xpra --help`, the server can only set the default value, the client is free to override it.

**Comment by Rush-iam** [comment]
But we don't have `speed` in `/html5/js/Client.js` (and don't have it in `default-settings.txt`).
Does this mean the HTML client will work with the `--speed` I specified when launching the server?

**Comment by totaam** [comment]
The `[min-]quality` and `[min-]speed` attributes can now be specified here:
https://github.com/Xpra-org/xpra-html5/blob/master/html5/default-settings.txt
