### ISSUE TITLE
Can provide an example of downloading files from client page?

### ISSUE THREAD

**Issue by shuimoshusheng** [Xpra-org/xpra-html5#270]
How to find the file download button in the HTML5 client when starting file transfer? After consulting the wiki tutorial, I couldn't find a detailed way to enable the file download function?

**Comment by shuimoshusheng** [comment]
> The download should just start and show up in the usual location of your browser. Without knowing more about your setup, it's impossible to give more details.

What is the default configuration for downloading display? access http://localhost:14500/ ，How to display the download on the page afterwards, with only the upload file button in the floating window

**Comment by totaam** [comment]
Please read the documentation:
https://github.com/Xpra-org/xpra/blob/master/docs/Features/File-Transfers.md
