### ISSUE TITLE
html mode WebRTC transport

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra-html5#28]
*Issue migrated from trac ticket # 1338*

**component:** html5 | **priority:** major | **keywords:** WebRTC AES html

#### 2016-10-11 21:29:19: JAremko created the issue

___
> Xpra html mode works over HTTP so it uses plain text URL. It means that a password and AES key can easily be intercepted.  But we can use WebRTC transport with or without signaling server.
> 
> Example: https://github.com/cjb/serverless-webrtc

**Comment by dakami** [comment]
A fair bit of sample code for how to do this is here:

https://cloud.google.com/architecture/gpu-accelerated-streaming-using-webrtc
https://cloud.google.com/architecture/orchestrating-gpu-accelerated-streaming-apps-using-webrtc

It's not the ... cleanest API I've ever seen, but you're doing a fair bit of this already IIRC.

**Comment by dakami** [comment]
https://github.com/selkies-project/selkies-vdi

...or, there's this.  I literally just bumped into it.

**Comment by totaam** [comment]
@dakami  that google cloud page compares with things like novnc, which don't have hardware acceleration.
And another key difference is how xpra manages windows instead of the whole display, which means that the windows are managed client side in the browser, without needing a roundtrip at all.
That's a huge saving right there, one that also makes it much more difficult to use webrtc. (we would need one webrtc context per window?)

**Comment by dakami** [comment]
They're using gstreamer's webrtc implementation, which calls back to nvenc.  Is xpra opening a nvenc context per window, and sending down a h.264 stream for each?  Not saying that's a bad architecture, just confirming it's pretty different than the flat framebuffer you correctly identify this code depends on.

**Comment by dakami** [comment]
Oh wow, xpra *is* that solution's CPU-only engine.  Cool!

**Comment by ehfd** [comment]
> They're using gstreamer's webrtc implementation, which calls back to nvenc. Is xpra opening a nvenc context per window, and sending down a h.264 stream for each? Not saying that's a bad architecture, just confirming it's pretty different than the flat framebuffer you correctly identify this code depends on.

Selkies-Gstreamer was recently released as a separate project, and yes, we have a different direction to Xpra. We are trying to implement something like Parsec, Shadow Gaming, Google Stadia, and GeForce Now on HTML5 with Linux as a host. It is also true that the VDI product of our original developer uses Xpra for CPU situations, but the WebRTC interface also has x264 encoding for software acceleration as well. We hope that Xpra grows with us.

**Comment by totaam** [comment]
> One webrtc context per window does look great to me. The video chat apps are already doing that with one video per participant, and possibly one screen sharing

That's a completely different use case though.
Participants do come and go, but not 5 times a second.
Every drop down menu, every tool tip, every menu is a separate window, and that's a lot of overhead.

**Comment by totaam** [comment]
Closing in favour of #3376 which is a much better fit.

As per [WebTransport](https://web.dev/webtransport/): _Generally, running a HTTP/3-compatible server requires less setup and configuration than maintaining a WebRTC server, which involves understanding multiple protocols ([ICE](https://developer.mozilla.org/docs/Web/API/WebRTC_API/Connectivity#ICE_candidates), [DTLS](https://webrtc-security.github.io/#4.3.1.), and [SCTP](https://developer.mozilla.org/docs/Web/API/RTCSctpTransport)) in order to get a working transport. WebRTC entails many more moving pieces that could lead to failed client/server negotiations._

**Comment by totaam** [comment]
Follow up in #143
