### ISSUE TITLE
JavaScript exception in HTML5 client version 11.1 'Uncaught TypeError: self.set_encoding_option is not a function'

### ISSUE THREAD

**Issue by jeffmax** [Xpra-org/xpra-html5#294]
**Describe the bug**
JavaScript exception in client.js when offscreen_api is true.

**To Reproduce**
Using a browser with offscreen_api available, connect to server using HTML5 11.1 client

**System Information (please complete the following information):**
 - Server OS: Ubuntu Jammy
 - Client OS: Mac OS x
 - Xpra Server Version 5.0.6
 - Xpra Client Version 11.1

**Additional context**
I think this line mistakenly uses `self` instead of `this`: https://github.com/Xpra-org/xpra-html5/blob/master/html5/js/Client.js#L547

**Comment by totaam** [comment]
Thanks for the report. The issue has been moved to `xpra-html5`.
This was caused by a buggy PR: #288

The commit above fixes it.
