### ISSUE TITLE
install from source needs root

### ISSUE THREAD

**Issue by thorstenwagner** [Xpra-org/xpra-html5#295]
Hi,

I noticed when running

```
git clone https://github.com/Xpra-org/xpra-html5
cd xpra-html5
./setup.py install
```

it requires root to create /etc/xpra

If I create with sudo, everythings works fine but I don't think that this is intentionally?

**Comment by totaam** [comment]
The html5 client installs a configuration file:
https://github.com/Xpra-org/xpra-html5/blob/1cbc65c8f4a3e7a49ff979d9b253539d540cd37a/setup.py#L20-L23
