### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by thorstenwagner** [Xpra-org/xpra-html5#300]
**Describe the bug**

I'm using Xpra 5.0.7 and I'm using the html5 client. 

When I'm using the html5 client via my laptop I'm observing a memory accumulation when doing certain things. What I do is running napari and within napari I trigger to calculate a UMAP on the GPU. I don't understand why I see a memory accumulation on my laptop?

Any ideas?

**Comment by thorstenwagner** [comment]
Its xpra-html version 12.0 beta

**Comment by totaam** [comment]
There are memory debugging tools in most browser's developer tools.

**Comment by totaam** [comment]
Not heard back.
