### ISSUE TITLE
Wrong Version of xpra-html5 in Ubuntu Jammy repository?

### ISSUE THREAD

**Issue by KriechelD** [Xpra-org/xpra-html5#302]
Looking at https://xpra.org/dists/jammy/main/binary-amd64/ the current latest Version ist `xpra-html5-12.0-r6-1.deb` published on 2024-03-29. But by default `xpra-html5-12.0-r1532-1.deb` gets installed. Testcase: 

Dockerfile
```
FROM ubuntu:jammy

# skip interactive configuration dialogs
ENV DEBIAN_FRONTEND noninteractive

# install Xpra from official sources
RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl curl gnupg && \
    UBUNTU_VERSION=$(cat /etc/os-release | grep UBUNTU_CODENAME | sed 's/UBUNTU_CODENAME=//') && \
    curl http://xpra.org/gpg.asc | apt-key add - && \
    echo "deb http://xpra.org/ $UBUNTU_VERSION main" >> /etc/apt/sources.list.d/xpra.list  && \
# Update again for xpra-html5
    apt-get update && \
    apt-get install -y xpra xpra-html5 && \
    apt-get -y --purge autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD apt show xpra-html5 | grep -i version
```

Run to Test:
`docker run --rm -it $(docker build -q .)`

Output:
![image](https://github.com/Xpra-org/xpra-html5/assets/3795587/e2bf7f58-cbc7-435d-8623-ef36e537e891)

**Comment by totaam** [comment]
Sorry about that, a beta build must have made it through the stable repo.

Should be fixed now, and I will make a new release soon anyway.
