### ISSUE TITLE
Cannot install from sdist.

### ISSUE THREAD

**Issue by gl-yziquel** [Xpra-org/xpra-html5#309]
Hi.

I like to generate artifacts so that I may install from artifacts and not only from source.

Basically, I did:

```console
./setup.py sdist
```

It creates an sdist.

However, running pip install on the sdist doesn't work. "invalid number of arguments". It obviously tries to run "python setup.py egg_info" but the script is not structured to be called with a "python" prefix.

**Comment by totaam** [comment]
There is no egg info to produce. 
Use `setup.py install`

**Comment by gl-yziquel** [comment]
The sdist target for setup.py is nonetheless advertised in `./setup.py`.

**Comment by totaam** [comment]
Because `sdist` can be used to generate source archives. 
This is how we publish releases.
