### ISSUE TITLE
xpra-html5 and xpra deploy same files in share/xpra/www

### ISSUE THREAD

**Issue by gl-yziquel** [Xpra-org/xpra-html5#310]
Having been attempting to build and install purely from source, I noticed that the `xpra` package deploys some but not all files in `share/xpra/www` and that `xpra`, via `./setup.py install`, installs kind of a superset.

They kind of step upon one another.

This induces problems in my personal build and packaging system as installing xpra and then xpra-html5 cannot be expected to produce the same results as installing xpra-html5 and then xpra. This lack of commutativity of installation sequence induces a lack of stability and reproducibility in deployment.

**Comment by totaam** [comment]
Please be specific.

**Comment by gl-yziquel** [comment]
Specific ? In what sense ?

What I see, for instance, is that both an installation of `xpra` and an installation of `xpra.html` each deploy a version of the `connect.html` file.

**Comment by totaam** [comment]
No, they do not.

**Comment by totaam** [comment]
See
https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs
And also the note about distribution packages.

**Comment by gl-yziquel** [comment]
Yes. They do. I am not using distribution packages. I am trying to find custom homegrown stable installation of xpra from pure source. It's me going around your build system trying to get xpra install in my .pyenvs.

I'm using commands like:

`./setup.py install /home/mini-me/.pyenv/versions/3.12.2/ /share/xpra/www`

And I do notice quite a lot of inconsistencies.

For instance:

'./setup.py install /home/yziquel/.pyenv/versions/3.12.2/' attempts to install in `/home/yziquel/.pyenv/versions/3.12.2/home/yziquel/.pyenv/versions/3.12.2/share/xpra/www` with duplicated prefix.

Now, you may say "this is not the way I support things", which is perfectly OK. Saying "you don't see what you see" is not quite the same thing...

For instance, this duplicate path prefix issue is tied to suboptimal handling of paths in setup.py. I consider that a bug.

**Comment by totaam** [comment]
The HTML5 client is not a python project and knows nothing about python.

The `xpra` package does not include any html pages.

**Comment by gl-yziquel** [comment]
I rechecked. Indeed. Scratching everything up and rebuilding and reinstalling xpra from scratch does not give me a share/xpra folder anymore. It is thus extremely unclear to me why I had a connect.html file there before having dabbled with xpra-html5.

Thank you. Will look at how to make my build from source + deployment procedures more robust.
