### ISSUE TITLE
Clipboard adding HTML Tags to pasted Text

### ISSUE THREAD

**Issue by zvooveDev** [Xpra-org/xpra-html5#316]
Describe the bug
After upgrading Xpra from version 4.4.6-r29-1 to 6.1-r0-1 (including updateing to Ubuntu 22.04) the clipboard is not working properly anymore when using the shortcut Strg+v.

To Reproduce

1. Use the newest Xpra version 6.1-r0-1
2. Configure in the HTML Client: "Clipboard sharing, preferred format: text/plain"
3. Copy a text from another tab of the Chrome Browser (in this sample: DE02120300000000202051)
4. Paste the text inside an edit box using Strg+v (right click + insert works as intended)
5. The text is enclosed in HTML Tags

Server OS: ubuntu:22.04
Client OS: Windows 11
Browser: Chrome 127.0.6533.73
Xpra Server Version 6.1-r0-1
Xpra Client Version 14
Application: Delphi Application running in Wine version 8.0.2
Additional context:

Using XPRA_CLIPBOARD_DEBUG I get the error 
`client ['xid=1400003', 'pid=459', "child of 'Xpra'"] is requesting an unknown target: 'text/plain'
 valid targets: text/html`
I attached the logs of the error using Strg+v (Clipboard_Unknown_Target.log) and the working paste by mouse (Clipboard_Working_Using_Mouse.log)

I can reproduce the error in 6.0-r0-1 and 5.0.9-r0-1
[Clipboard_Unknown_Target.log](https://github.com/user-attachments/files/16425622/Clipboard_Unknown_Target.log)
[Clipboard_Working_Using_Mouse.log](https://github.com/user-attachments/files/16425619/Clipboard_Working_Using_Mouse.log)

**Comment by totaam** [comment]
@zvooveDev c5c8cf6de46633cca45a2df8dce8d02f38e0ed16 looks like the correct fix.
But, since I failed to test this properly before the release, and again after you submitted this ticket... I will take another look tomorrow to make sure.

**Comment by zvooveDev** [comment]
> @zvooveDev [c5c8cf6](https://github.com/Xpra-org/xpra-html5/commit/c5c8cf6de46633cca45a2df8dce8d02f38e0ed16) looks like the correct fix. But, since I failed to test this properly before the release, and again after you submitted this ticket... I will take another look tomorrow to make sure.

The commit has fixed the problem. Thank you

**Comment by totaam** [comment]
Thanks.
I will push a new release with this fix, hopefully today.

**Comment by totaam** [comment]
v15 includes this fix:
https://github.com/Xpra-org/xpra-html5/releases/tag/v15
