### ISSUE TITLE
Single Application streaming / Reuse of Xpra session?

### ISSUE THREAD

**Issue by MrMEEE** [Xpra-org/xpra-html5#318]
Hi

I'm trying to use xpra-html5 (other suggestions are welcome), to create a game streaming service (local) for old dos/win98 games. 

Basically there will be an interface, where users (my kids) can login and then choose a game. Then the game (dosbox driven) will spawn in on the website through xpra..

I can probably spawn an xpra service when the user logs in, but is there a way to reuse the same service, but launch different applications? or do I have to kill off the xpra service for the user, every time they select a new game?

Regards

**Comment by totaam** [comment]
This is not really an xpra question, it's more of a service setup issue.

> I can probably spawn an xpra service when the user logs in

Logs in how and where?

It's very difficult to answer your questions with so many details missing.

**Comment by MrMEEE** [comment]
> This is not really an xpra question, it's more of a service setup issue.
Yeah, I know.. but hoped that someone could be helpful anyways :)

> > I can probably spawn an xpra service when the user logs in
> Logs in how and where?
Into the interface that I'm designing.. I think the biggest question here is if it's possible to reuse a started xpra session, and start another process when logging in?

Hope that it makes sense..

**Comment by totaam** [comment]
> if it's possible to reuse a started xpra session

Possible, yes. Desirable, not always.

> start another process when logging in

`--start-on-connect=foo`
