### ISSUE TITLE
Set fixed resolution not working

### ISSUE THREAD

**Issue by NN-Binary** [Xpra-org/xpra-html5#320]
Hi, I've tried I believe everything from the manual, from desktop-scaling, to resize-display, to adjusting xpra.conf but I can't seem to have a FIXED resolution (1024x768) on the HTML5 client.

I cant' seem to make the scaling work either, the GET param `override_width` doesn't do anything as well in the HTML5 client

Does anyone have a concrete example on how to set a fixed resolution 1024x768 and use scaling? My goal is to see it in a small window of half size.

OS: Debian 12, but I've tried on Linux Mint too

**Comment by totaam** [comment]
This was added in #57 - I have never used it myself, perhaps the original author of this PR can help you? @basilgello

**Comment by basilgello** [comment]
Are you sure Debian 12 has Xpra with this fix? Thst commit was added in v4.3 but Debian still has 3.1.5: https://tracker.debian.org/pkg/xpra because original Debian maintainer of xpra rejected my efforts to package newer Xpra.

**Comment by totaam** [comment]
@NN-Binary I have just tried to launch a desktop session with a fixed resolution and needed this fix: https://github.com/Xpra-org/xpra/commit/27ccf0e88d8d9dae33ca9b925007bd00596ac249
Then I can run:
```
xpra start-desktop --start=xterm --resize-display=off:720p
```
To get a 720p desktop session that cannot be resized.
The html5 client draws the desktop background around the edges.
