### ISSUE TITLE
Missing start menu (again) with xpra versions from 6.1

### ISSUE THREAD

**Issue by TermeHansen** [Xpra-org/xpra-html5#321]
Not sure if this is related to this old issue
https://github.com/Xpra-org/xpra-html5/issues/263

But the symptom is at least the same :) I have no start menu with xpra versions from 6.1 and up. "6.0.2-r0-1" seems to be he last version that works for me.

Running latest xpra-html5 (version 16), so not strictly related to a change here. Any ideas?

**Comment by totaam** [comment]
@TermeHansen what OS / distro / etc?
What version of the html5 client?
Anything in the server log?
I'm going to guess Ubuntu?

**Comment by TermeHansen** [comment]
@totaam Yes, it is on Ubuntu (22.04 still), the html5 client is latest, version 16 as I write. 

Initially I tried going back versions of the html5 client to version 13 with no difference. 

This particular server is used in a work setup, so I'll see if I can reproduce on another server and check logs or check again when the server is not in use next time...

**Comment by sbradnick** [comment]
I'm having this issue as well with an xpra-html5 build up to b0457c1 ; was previously using 4fe30fc and don't recall having this issue - but maybe I didn't check.

xpra is running from Xpra-org/xpra@469f9329 (August 26th)

Client and Server are both OpenSUSE Tumbleweed.

**Comment by totaam** [comment]
@sbradnick ah, damn.
Trivial fix in 0aa77036fb9ffadff54aa98cc6d9d235d5531d08.
I will cut another release soon.

**Comment by sbradnick** [comment]
> @sbradnick ah, damn.
> Trivial fix in [0aa7703](https://github.com/Xpra-org/xpra-html5/commit/0aa77036fb9ffadff54aa98cc6d9d235d5531d08).
> I will cut another release soon.

The menu has returned, thanks!
