### ISSUE TITLE
protocol error: invalid packet header format: 100: 0x646973636f6e6e65

### ISSUE THREAD

**Issue by MoritzWeber0** [Xpra-org/xpra-html5#328]
We've recently updated our Xpra HTML5 client from version 10.1 to 16.2. Unfortunately, the stability has decreased massively. 
During the initial connection, it reloads several times, then loads and after ~10 seconds of of a stable connection, it drops the connection. We didn't see those issues with version 10.1. The Xpra version itself didn't change and is `v6.2.1-r0`.

The connection always drops with the following error message (`protocol error: invalid packet header format: 100: 0x646973636f6e6e65`):  
![image](https://github.com/user-attachments/assets/f1a6e71e-4e91-4712-bb0f-90f3f402064e)

It's always exactly the same message.

The logs of Xpra don't contain any valuable information, but here is the more interesting [console.log](https://github.com/user-attachments/files/17619991/console.log).

We run Xpra behind an nginx reverse proxy, but the configuration is rather simple: 

```
# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

pid /tmp/nginx.pid;
daemon off;
events{}
http {
    # These options are needed to run as non-root
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    server {
        listen 10000;
        server_name _;

        root /usr/share/nginx/html;
        error_page 502 /error.html;
        error_page 404 /error.html;

        location __XPRA_SUBPATH__ {
            rewrite ^__XPRA_SUBPATH__(.*) /$1 break;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_pass http://127.0.0.1:10001;
            proxy_buffering off;

            proxy_hide_header Content-Security-Policy;
            add_header Content-Security-Policy "frame-ancestors self __XPRA_CSP_ORIGIN_HOST__";
        }
    }
}
```

**Comment by totaam** [comment]
Can you reproduce these issues without your reverse proxy?

**Comment by MoritzWeber0** [comment]
I spent a bit of time investigating it in more detail. The HTML5 client seems to be a lot less resilient to slow internet connections than the 10.1. It tries to reconnect quickly while the old version tried to keep the connection alive. 

It's reproducible with a local running Xpra (without any reverse proxy in the way) when throttling is enabled in the Chrome Dev-Tools. When I change it to `Slow 4G` and reload the page, it tries to reconnect a few times (connection loop) and sometimes I could also see the above error message.

**Comment by totaam** [comment]
What does the JavaScript console show when the reconnect triggers?

**Comment by MoritzWeber0** [comment]
The full `console.log` is attached to the ticket, but the relevant messages during dropped connection are: 

```
Utilities.js:1 audio-state: stopped
Utilities.js:1 cancel_all_files( closing ) will cancel: []
Utilities.js:1 connection-lost
Utilities.js:1 connection_progress( Connecting to server ,  example.com:443/session/dfgjeumbgeknvzvbhdtavqlps/ with ssl ,  40 )
```

**Comment by MoritzWeber0** [comment]
I just see that the attached console.log has reconnect disabled. Here is another log from my local environment: 
[localhost-1730798765859.log](https://github.com/user-attachments/files/17630140/localhost-1730798765859.log)

The main issue for the connection losses is probably that the ping runs into a timeout: 
```
Utilities.js:1 ping timeout - reconnecting
console_warn_safe @ Utilities.js:1
cwarn @ Client.js:1
warn @ Client.js:1
_check_echo_timeout @ Client.js:1
(anonymous) @ Client.js:2
setTimeout
_send_ping @ Client.js:2
(anonymous) @ Client.js:2
setInterval
_process_hello @ Client.js:2
_route_packet @ Client.js:1
(anonymous) @ Client.js:1
(anonymous) @ Protocol.js:1
Utilities.js:1 close_audio_mediasource: audio_source_buffer=undefined, media_source=undefined, audio=null
Utilities.js:1 audio-state: stopped
Utilities.js:1 cancel_all_files( closing ) will cancel: []
Utilities.js:1 connection-lost
```

Is there a way to configure the default timeout? 

The "initial connection loop" has the following trace in the console.log: 

```
Utilities.js:1 connection-established
Protocol.js:1 protocol error: invalid packet header format: 100: 0x646973636f6e6e65
error @ Protocol.js:1
protocol_error @ Protocol.js:1
do_process_receive_queue @ Protocol.js:1
process_receive_queue @ Protocol.js:1
(anonymous) @ Protocol.js:1
setTimeout
websocket.onmessage @ Protocol.js:1
Utilities.js:1 websocket closed:  invalid packet header format: 100: 0x646973636f6e6e65 reason:  null , reconnect:  true , reconnect attempt:  0
Utilities.js:1 connection-lost
Utilities.js:1 websocket closed:  'Normal Closure' (1000): 'unknown reason' reason:  invalid packet header format: 100: 0x646973636f6e6e65 , reconnect:  true , reconnect attempt:  1
```

**Comment by MoritzWeber0** [comment]
If you can't reproduce it locally, I can offer a Docker image that runs Xpra with an instance of Eclipse Capella (that's what we use in production). It's relatively large though. 

```zsh
docker run -p 10000:10000 -e CONNECTION_METHOD=xpra ghcr.io/dsd-dbs/capella-dockerimages/capella/remote:7.0.0-without-dropins-v2.7.0
```

After it's pulled and started, connect to: http://localhost:10000/
Then go to the dev tools in the browser, open the Network tab, add 3G as network throttling, and refresh the page. After a bit of waiting time, it will go into a reconnect loop.

**Comment by MoritzWeber0** [comment]
To be a bit more specific, the error occurs with version v16, but not with v15.1. It must have to with changes between those releases: https://github.com/Xpra-org/xpra-html5/compare/v15.1...v16

**Comment by totaam** [comment]
The obvious change affected by `OPEN_TIMEOUT` is 8614719f724b06ce99a9fb1f3093464274ad5d25 for https://github.com/Xpra-org/xpra-html5/issues/317#issuecomment-2303840545

There are a number of proxy related issues too: https://github.com/Xpra-org/xpra-html5/issues/317, https://github.com/Xpra-org/xpra-html5/issues/299#issuecomment-2047891576, https://github.com/Xpra-org/xpra/issues/1349#issuecomment-765469689

Aside from fixing the obvious bugs, we should probably have an nginx reference config and documentation.

**Comment by totaam** [comment]
I have bumped the `OPEN_TIMEOUT` to 10 seconds, which should be more than enough to open a websocket connection.

@MoritzWeber0 is this enough for you?

**Comment by MoritzWeber0** [comment]
Hi @totaam,

thanks a lot, especially for the modal dialog fix! I'll try the modified TIMEOUT over the new weeks and will report back if it has solved the issue (takes some time because it's hard to reproduce and only appears sometimes).
