### ISSUE TITLE
--key-shortcut not working on ubuntu 20.04

### ISSUE THREAD

**Issue by rohitdesaidev** [Xpra-org/xpra-html5#33]
Hi I am new to Xpra and I am trying to use local html client to test my requirement, 
When I use  `xpra start --bind-tcp=0.0.0.0:10000 --start=xterm --key-shortcut='Alt+F10':toggle_fullscreen` to launch the application in fullscreen it wont work. Can someone help me whats the wrong I am doing in command line or is there something else I am missing. Attaching log file for reference. 
[:2.log](https://github.com/Xpra-org/xpra-html5/files/5883324/2.log)

**Comment by totaam** [comment]
The `key-shortcut` option is only applicable to the xpra client (`xpra attach`), not the server (ie: `xpra start`)

There are currently no shortcuts in the HTML5 client to make a window go fullscreen, though this could be added easily enough.
We could also add this option to the window title bar.

Instead, you could just use `xdotool` and the `--start-on-connect` option. ie:
```
xpra start --start-on-connect=/usr/local/bin/fullscreen-script.sh --start=xterm --bind-tcp=0.0.0.0:10000
```
And in your `fullscreen-script.sh`, use `xdotool` to make your application window fullscreen.
This script will fire every time a client connects.

**Comment by rohitdesaidev** [comment]
Thank you so much @totaam for your response, this was helpful to understand the commands for client.
With the solution you provided does the HTML5 client goes fullscreen or the application which we launch through the --start goes fullscreen ? As I wanted to make application launch in fullscreen not in respect with client screen. 
Thanks again for the solution I will try the same on my linux machine.

**Comment by totaam** [comment]
> does the HTML5 client goes fullscreen or the application which we launch through the `--start` goes fullscreen ?

`xdotool` can make the application "fullscreen" server side, and since the server-side virtual screen matches your browser window size, it will completely fill the browser window. (making the browser window itself go fullscreen is impossible using javascript)

**Comment by rohitdesaidev** [comment]
Seems perfect solution for my requirement, thank you so much for your help I appreciate it.
