### ISSUE TITLE
src/html5/js/Utilities.js refers to non-existent MPL-2.1

### ISSUE THREAD

**Issue by onlyjob** [Xpra-org/xpra-html5#35]
`src/html5/js/Utilities.js` refers to incorrect license (with broken URL):

```
 * Licensed under MPL 2.1, see:
 * http://www.mozilla.org/MPL/2.1/
```
Probably due to a typo: only __MPL-2.0__ is valid: http://www.mozilla.org/MPL/2.0/

**Comment by totaam** [comment]
Thanks, this is a case of search and replace gone wrong: 8c547b91e32f6e07b9d70c9eb6224df6ab66daa2

Fixed in be75d54b5772bd023c1f8bff8938dbe5684afbf6
