### ISSUE TITLE
official xpra.org repo: package architecture (any) does not match system (amd64) 

### ISSUE THREAD

**Issue by brainopener** [Xpra-org/xpra-html5#37]
I'm running in this environment:
```
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-16-amd64
Architecture: x86-64

```

I have this apt file configured:
```
md5sum /etc/apt/sources.list.d/xpra.list 
2a8d31fdbba761b4014f0e5a54e9eef0  /etc/apt/sources.list.d/xpra.list

```

I already have these `xpra` and `xpra-html` packages installed:

```
sudo apt list --installed | grep xpra

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

xpra-html5/buster,now 4.0.6-r28351-1 amd64 [installed,upgradable to: 4.1]
xpra/buster,now 4.1.1-r28-1 amd64 [installed]

```

When attempting to update, I'm getting an error message `package architecture (any) does not match system (amd64)` --- see below.

```
sudo apt update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                            
Hit:3 http://deb.debian.org/debian buster-updates InRelease                    
Ign:4 https://ookla.bintray.com/debian buster InRelease                        
Get:5 https://xpra.org buster InRelease [4,081 B]
Get:6 https://ookla.bintray.com/debian buster Release [4,387 B]
Get:7 https://xpra.org buster/main i386 Packages [48.2 kB]
Get:9 https://xpra.org buster/main amd64 Packages [55.3 kB]
Fetched 112 kB in 1s (77.2 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.

```

```
sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  xpra-html5
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/402 kB of archives.
After this operation, 5,014 kB disk space will be freed.
Do you want to continue? [Y/n] y
Reading changelogs... Done
dpkg: error processing archive /var/cache/apt/archives/xpra-html5_4.1_amd64.deb (--unpack):
 package architecture (any) does not match system (amd64)
Errors were encountered while processing:
 /var/cache/apt/archives/xpra-html5_4.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by callegar** [comment]
Same issue with ubuntu focal.

**Comment by totaam** [comment]
Sorry about that. My bad.
According to https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-architecture *all, which indicates an architecture-independent package* and I had used `any` instead.

**Comment by olifre** [comment]
@totaam Thanks for the fix! 
Reading through:
https://wiki.debian.org/Multiarch/Implementation#Multi-Arch:_foreign_support_packages
I believe that:
`Multi-Arch: foreign`
should also be set (albeit it seems that it is not enforced for `Architecture: all` packages as of now).

**Comment by brainopener** [comment]
I am confirming the fix.

```
...
sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  xpra-html5
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 402 kB of archives.
After this operation, 5,014 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://xpra.org buster/main amd64 xpra-html5 all 4.1.1 [402 kB]
Fetched 402 kB in 1s (358 kB/s)     
Reading changelogs... Done
(Reading database ... 146052 files and directories currently installed.)
Preparing to unpack .../xpra-html5_4.1.1_all.deb ...
Unpacking xpra-html5 (4.1.1) over (4.0.6-r28351-1) ...
Setting up xpra-html5 (4.1.1) ...

```

**Comment by olifre** [comment]
While it also works for me on Buster, it still fails on Ubuntu Bionic:
```
Unpacking xpra (4.1.1-r28-1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-19FWTx/105-xpra-html5_4.1_amd64.deb (--unpack):
 package architecture (any) does not match system (amd64)
```
Maybe the rebuild is still ongoing for that platform?

**Comment by olifre** [comment]
To exclude this is a caching issue on my end (I have an HTTP proxy here), I checked at:
http://xpra.org/dists/bionic/main/binary-amd64/
and indeed http://xpra.org/dists/bionic/main/binary-amd64/xpra-html5-4.1.1-1.deb still contains `Architecture: any`.

**Comment by totaam** [comment]
@olifre Sorry about that, there were so many packages for all the distros that I failed to spot that the Ubuntu Bionic build was missing.  
The container had failed with `error creating container: the container name "ubuntu-bionic-xpra-build-temp" is already in use by ...` from an earlier aborted build.

I nuked it and ran the build again.
I have also tested this in a VM and the update now goes through.

Note: the package is an update with version `4.1.1-3` (we don't replace packages in place to avoid caching issues).

**Comment by olifre** [comment]
@totaam Many thanks, I can confirm it works now :-). We have an automated container build here which retried every hour, so I had nice monitoring (by hourly mails). 
If your CI allows it, it might be interesting to add an installation step in a separate VM / container to catch such issues. 
In case you missed my comment above, I believe `Multi-Arch: foreign` (albeit somewhat redundant) might be needed in the `control` files (not yet enforced by Debian for `Architecture: all` packages), just mentioning this in case it might be required at some point.

**Comment by totaam** [comment]
Yes, I am converting the buildbot into a CI system. Slowly.

As for the `Multi-Arch: foreign` option, I've read up on it and it's still not clear to me why this would be needed for a pure noarch package with only noarch dependencies.  
This bit does worry me: *If a package is declared Multi-Arch: foreign, preference should be given to a package for the native architecture if available*  
What about version numbers? Which one takes precedence? Does that mean that if I set this option then an older arch specific version would take precedence? Or is this only for packages of the same version?

**Comment by olifre** [comment]
> Yes, I am converting the buildbot into a CI system. Slowly.

That sounds great :-). 

> As for the `Multi-Arch: foreign` option, I've read up on it and it's still not clear to me why this would be needed for a pure noarch package with only noarch dependencies.

I think the concept becomes more clear in this explanation:
https://wiki.debian.org/MultiArch/Hints#set_Multi-Arch:_foreign
If I understand correctly, an example would be this one: 
Let's imagine somebody would create a separate package using the `xpra-html5` client. For this example, let's assume it is called `xpra-browser` (i.e. somebody writes a browser relying on the HTML5 parts).  Let's further assume this browser is of `Multi-Arch: same`, and ships an `i386` and `amd64` package. `Multi-Arch: same` means these are co-installable, i.e. I can install the 32 bit and 64 bit variant of that browser at the same time. So it likely will install something lie `xpra-browser-32` and `xpra-browser-64` as binary, may expose that via `update-alternatives?, use separate `lib` directories, and so on. 

Now, we run into the issue: `xpra-html5` on an `amd64` machine with `Architecture: all`, but without `Multi-Arch: foreign` will install just fine first, but after installation is treated "as if it was of the native architecture". Then, I want to install the `xpra-browser` in both the 32 bit and 64 bit flavour (stuff like this tends to happen especially with WINE, which is often used in the 32 bit variant also on 64 bit systems). This now fails, since  `xpra-html5` can not satisfy the dependency of `xpra-browser` in the 32 bit variant. 

>  What about version numbers? Which one takes precedence? Does that mean that if I set this option then an older arch specific version would take precedence? Or is this only for packages of the same version?

I am quite certain this is only for packages of the very same version, otherwise, the ongoing migration to `MultiArch` would be impossible. Sadly, I did not find an explicit reference to this (will keep looking).

**Comment by totaam** [comment]
Thanks for the detailed explanation. Added above.

**Comment by olifre** [comment]
Thanks to you :+1: .
