### ISSUE TITLE
xpra-html5 4.1.2 fails in desktop Safari (4.0.6-r28351-1 works)

### ISSUE THREAD

**Issue by brainopener** [Xpra-org/xpra-html5#39]
I'm running Safari 14.0.3 on MacOS 11.2.3.

It looks like something has happened between 4.0.6-r28351-1 and 4.1.2 to fail to function in Safari. In this case, this is a fresh install of xpra and xpra-html5 on a fresh Debian Buster.

Here's what it looks like from the browser side:
![attempt](https://user-images.githubusercontent.com/2715861/113418095-d0a64d00-9392-11eb-803b-63210e99aa92.gif)

It connects, errors, disconnects, repeats a few times. Also, notice that it has activated the on-screen keyboard --- that's new behavior since 4.0.6-r28351-1 (I'm wondering if it thinks it is on Safari on iOS). Chromium and FireFox on this same Mac have no issue --- no extra keyboard and connects just fine.

Looking in the Safari Javascript console, I do notice these errors:
```
[Error] error decoding packet TypeError: TypedArray.from requires its this argument subclass a TypedArray constructor
	(anonymous function) (Protocol.js:1:3568)
	(anonymous function) (Protocol.js:1:6452)
	(anonymous function) (Protocol.js:1:3493)
	(anonymous function) (Protocol.js:1:2882)

[Error] protocol error: – "too many raw packets: 6"
	(anonymous function) (Protocol.js:1:3568)
	(anonymous function) (Protocol.js:1:3188)
	(anonymous function) (Protocol.js:1:6159)
	(anonymous function) (Protocol.js:1:3493)
	(anonymous function) (Protocol.js:1:2882)
```

Screenshot of console for context:
<img width="600" alt="errors" src="https://user-images.githubusercontent.com/2715861/113418714-04ce3d80-9394-11eb-98cf-310e8a181c86.png">

**Comment by totaam** [comment]
This was caused by the new rencoder (#18).

The fix above just disables rencode with Safari, as I couldn't figure out what was wrong with it.
Maybe @TijZwa can fix it.
