### ISSUE TITLE
How to customize HTML5 connect.html webinterface

### ISSUE THREAD

**Issue by TillKoch** [Xpra-org/xpra-html5#41]
Hi 
can anybody direct me on how to customize the HTML5 Webserver?

I would like to have two things:
- customize the options/settings that a user can set on `connect.html`
- permanently hide the floating menu on `index.html` after sucessfull login

Thanks!

**Comment by totaam** [comment]
> customize the options/settings that a user can set on `connect.html`

This page is just straightforward HTML and Javascript. Any junior developer can customize it.

> permanently hide the floating menu on `index.html` after sucessfull login

The floating menu already has an option on the connect page.  
The option is named `floating_menu` so a URL like `XXXX/index.html?floating_menu=0` should hide it.
