### ISSUE TITLE
Files are randomly skipped during minifying

### ISSUE THREAD

**Issue by arrowd** [Xpra-org/xpra-html5#42]
When building `xpra-html5` on FreeBSD I get the following output:

```
minified js/Menu-custom.js
minified js/lib/AudioContextMonkeyPatch.js
minified js/lib/jsmpeg.js
Error: failed to minify 'pyrencoder.js', command ['yuicompressor', '/wrkdirs/usr/ports/x11/xpra-html5/work/xpra-html5-4.1.2/html5/js/lib/pyrencoder.js.tmp', '--nomunge', '--line-break', '400', '--type', 'js', '-o', '/wrkdirs/usr/ports/x11/xpra-html5/work/stage/usr/local/share/xpra/www/js/lib/pyrencoder.js'] returned error 2
minified js/lib/pyrencoder.js
Error: failed to minify 'jquery.js', command ['yuicompressor', '/wrkdirs/usr/ports/x11/xpra-html5/work/xpra-html5-4.1.2/html5/js/lib/jquery.js.tmp', '--nomunge', '--line-break', '400', '--type', 'js', '-o', '/wrkdirs/usr/ports/x11/xpra-html5/work/stage/usr/local/share/xpra/www/js/lib/jquery.js'] returned error 2
minified js/lib/jquery.js
minified js/lib/FileSaver.js
minified js/lib/wsworker_check.js
minified js/lib/zlib.js
minified js/lib/bencode.js
copied js/lib/zlib.pretty.js.map
minified js/lib/forge.js
minified js/lib/jquery.ba-throttle-debounce.js
copied js/lib/simple-keyboard.js.map
minified js/lib/jszip.js
Error: failed to minify 'simple-keyboard.js', command ['yuicompressor', '/wrkdirs/usr/ports/x11/xpra-html5/work/xpra-html5-4.1.2/html5/js/lib/simple-keyboard.js', '--nomunge', '--line-break', '400', '--type', 'js', '-o', '/wrkdirs/usr/ports/x11/xpra-html5/work/stage/usr/local/share/xpra/www/js/lib/simple-keyboard.js'] returned error 2
minified js/lib/simple-keyboard.js
minified js/lib/lz4.js
minified js/lib/jquery-ui.js
minified js/lib/es6-shim.js
```

Problematic files are different each time I run the build. I suspect it might be related to the fact that `yuicompressor` on FreeBSD is a shellscript that calls `java` under the hood. Maybe `Popen` doesn't wait for a process to finish?

**Comment by arrowd** [comment]
Sorry for the inaccurate info, it is always

```
jquery.js
pyrencoder.js
simple-keyboard.js
mp3.js
```

that are failing.

**Comment by arrowd** [comment]
`simple-keyboard.js` fails due to syntax error, so it looks like upstream issue (simple-keyboard or yuicompressor).

Other ones fails due to missing `.tmp` file.

**Comment by totaam** [comment]
`yuicompressor` does not support the newer syntax used in those files.

Use `uglifyjs` if you care about this minor problem.

**Comment by arrowd** [comment]
What about `jquery.js` and others?

**Comment by totaam** [comment]
`jquery.js` you should be getting a symlink to the one from your distro, and therefore can't be minified.

Others, I don't know.

**Comment by arrowd** [comment]
If I read the code correctly, the symlink is created only if the distro provides `jquery.js`. This is not the case for me, so the bundled one should be minified. It works when the minifier is set to `copy`.

**Comment by totaam** [comment]
> If I read the code correctly, the symlink is created only if the distro provides jquery.js.

Correct.

>  This is not the case for me, so the bundled one should be minified. It works when the minifier is set to copy.

If your distro's minifier can't handle your distro's version of jquery... then there's not much we can do, is there?
