### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by ZhaoZuohong** [Xpra-org/xpra-html5#49]
In the _installation_ section, the path is incorrect: it should be `/usr/share/xpra/www` but not `/usr/share/www/xra`.
By the way, it needs `uglifyjs` to be installed when using `setup.py install`.

**Comment by totaam** [comment]
> In the installation section, the path is incorrect

Thanks, fix above.

> By the way, it needs `uglifyjs` to be installed when using `setup.py install`.

It is optional but not auto-detected yet, if you don't have it installed use:
```shell
./setup.py install /some/path ""
```
