### ISSUE TITLE
On-screen keyboard appears on PCs

### ISSUE THREAD

**Issue by lm-sig** [Xpra-org/xpra-html5#50]
Commit b588681 says it should only show for phones or tablets.

It is very visible on Windows 10 PCs with physical USB keyboards and mice.

Xpra 4.1.2 from the xpra.org official repository:
xpra-4.1.2-10.r78.el8.x86_64
xpra-html5-4.1.2-1.noarch

Server OS: RHEL 8.4
Client Browser: Firefox 78.10.0esr

**Comment by totaam** [comment]
Already fixed: https://github.com/Xpra-org/xpra-html5/issues/47#issuecomment-832750750

This will be in the next stable update.
