### ISSUE TITLE
HTML5 file upload fails on xpra 4.1-r28292

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra-html5#6]
*Issue migrated from trac ticket # 2993*

**component:** html5 | **priority:** critical

#### 2021-01-04 22:28:37: ffeldhaus created the issue

___
> I regularly use file uploads with my wireshark docker image which is using xpra (https://github.com/ffeldhaus/docker-wireshark). With the current stable xpra version 4.0.6-28284 on Ubuntu 20.04, I can upload files normally. With the latest xpra beta 4.1-28292 I get this error when uploading files via the HTML5 client:
> 
> ```
> 2021-01-04 22:15:27,670 client   1 file: 8m , type:  , size: 8388608
> 2021-01-04 22:15:31,447 Error: invalid data size for file '8m'
> 2021-01-04 22:15:31,448  received 12581964 bytes, expected 8388608 bytes
> ```
> 
> 
> The xpra config files and setup are the same, but I use Ubuntu 20.04.1 LTS for running xpra stable and Ubuntu 20.10 to run xpra beta.

**Comment by oeway** [comment]
Hi @totaam I am also having trouble with file upload, not sure if it's same issue as this one. But when I select a file through the upload menu, nothing happens, but when I open the terminal and check the home folder, I can see the file listed with size = 0.

I am using `xpra v4.2.1-r0` with `xpra-html5 v4.3` in Ubuntu bionic.

**Comment by totaam** [comment]
Fixed in b8812c0365091ecb755c8b39cd2e1a0b52988b7a.
