### ISSUE TITLE
color artifacts during refresh

### ISSUE THREAD

**Issue by goekce** [Xpra-org/xpra-html5#63]
Using xpra 3004e3d.

Remote desktop using Firefox 89.0.1 and Chromium show the following color artifacts when I move my mouse. They are gone after maximum 5 seconds.

![image](https://user-images.githubusercontent.com/18174744/122197615-a72c9600-ce98-11eb-8452-21329ee9a89f.png)

When I fire up Firefox on remote desktop I do not see these effects. It may be dependent on the GUI toolkit. The screenshot is from an industrial, rather older Eclipse environment.

No color artifacts when I use the native Xpra client.

How can I further debug the problem?

**Comment by totaam** [comment]
This looks absolutely awful!

Can you run the server with `-d compress` and see what these updates correspond to?
You can also get the same information in visual form by enabling `draw` debugging from the connect dialog. The colors are documented here:
https://github.com/Xpra-org/xpra-html5/blob/d5d0bff8389479a1c8e833bd0e50917a580c071f/html5/js/Window.js#L1277-L1292

**Comment by totaam** [comment]
Not heard back. I assume this is fixed, never seen this myself and if others had, I would know.
