### ISSUE TITLE
Inconsistent version number

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#76]
Hi, I noticed that in the html file it said version 4.1.1 (https://github.com/Xpra-org/xpra-html5/blob/5db00075c1962032d9f1aa3fcbf40628ef6e24f3/html5/index.html#L147), but in the setup.py file, the version number is 4.3. Which one is correct?

**Comment by totaam** [comment]
Oops. Thanks for the report.
The commit above should prevent that in the future.
