### ISSUE TITLE
Transparent pixels in the window edges

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#79]
This is a minor issue but would be nice to fix anyhow. 

And for Java windows, there are a few pixel spaces that are always transparent in the bottom edges. Other 3 edges still have 1~2 transparent pixels.
 
The screenshot below is a java dialog:
<img width="489" alt="Screen Shot 2021-07-30 at 1 19 23 PM" src="https://user-images.githubusercontent.com/478667/127645690-b6c937bb-4e83-426b-a937-862275ecda59.png">

For non-java window, e.g. the terminal, I can still see 1~2 pixel transparent for all the 4 edges of the window.

If there is no easy way to fix, it might be better to fill with white pixels to avoid the distracting effect on the window edges.

EDIT: In fact when I look closer, the transparent pixel depends on the position of the window, if I drag the window slowly, I saw the empty pixel of the edge disappearing and appearing.

**Comment by totaam** [comment]
> "the terminal"

Which terminal application?
Did you resize it?
Can you grab `xpra info` when this happens?

**Comment by oeway** [comment]
I noticed that the transparent pixels only happens when I set the zoom level to, e.g. 175% in the browser.

This is the xpra info with 175% zoom level which produce these transparent pixels: [175%-zoom-xpra-info.txt](https://github.com/Xpra-org/xpra-html5/files/6911572/175.-zoom-xpra-info.txt)

And this is the normal xpra info when the zoom level is 100% without the transparent pixels: [normal-xpra_info.txt](https://github.com/Xpra-org/xpra-html5/files/6911574/normal-xpra_info.txt)

Note that the bottom transparent pixels always appears for java windows disregards the zoom levels.

**Comment by totaam** [comment]
> only happens when I set the zoom level to >125%, e.g. 175%

Right, this only happens with fractional scaling. 200% or 300% don't have this problem.
My guess is that the window dimensions end up rounded up by the browser and so there are pixels on-screen that we have no backing data for.
I'm not sure how to fix this:
https://github.com/Xpra-org/xpra-html5/blob/4dcf1b01119f40476bc2e318d09eb39f558024f5/html5/js/Window.js#L1098
As the scaling is done transparently by the browser.
We can detect that scaling is being used:
```
window.devicePixelRatio
1.75
```
But if we used this value to provide higher resolution window pixel data, in most cases the window sizes would stay the same as the zoom is increased to maintain the same number of pixels shown... which is generally not what the user wants.
Some useful info here: [draw in high resolution to canvas on Chrome](https://stackoverflow.com/questions/19142993/how-draw-in-high-resolution-to-canvas-on-chrome-and-why-if-devicepixelratio)

> BTW, when we drag the window slowly, the windows doesn't move smoothly as if they try to snap into some hidden grid, is there any reason for that?

I'm not seeing this with *any* applications, please open a separate ticket for this issue with more details.

**Comment by oeway** [comment]
OK, this is not a big issue since the zooming of the browser is not a very common use case. Feel free to close.
