### ISSUE TITLE
Minor UI improvement suggestions

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#80]
Hi, thanks for your great work! I was collecting feedbacks from my users and they have two minor UI style improvement suggestions which I also think are reasonable: 
 1) Use a Sans Serif font (e.g. `font-family: Arial, Helvetica, sans-serif;`) for the window title because that's the default font style for most native windows in Ubuntu, MacOS etc.
 2) Perhaps make the title bar background white when it's active (and gray when it's inactive) because black font color looks sharper with black background.

**Comment by totaam** [comment]
The commits above should do what you want.

**Comment by oeway** [comment]
Thanks a lot for your rapid fix, you are amazing!
