### ISSUE TITLE
Control key in MacOS

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#81]
The current `ctrl` key mapping doesn't seem correct for MacOS, it maps the `command` key to `ctrl` so when we want to send a `ctrl+c` command to terminate a program in a terminal we need to press `Command+C` instead of `Control+C`. I think it will be much more natural if we can use the `control` key as `ctrl` for client running on MacOS.

In addition,  it seems also reasonable to translate `command+c` and `command+v` into `ctrl+shift+c` and `ctrl+shift+v` so we can easily copy and paste in a terminal. If not done by default, is there a way that we can define this type of mapping?

**Comment by totaam** [comment]
The connect page includes an option: _Swap command and control key_ which defaults to being enabled on MacOS.

**Comment by oeway** [comment]
> The connect page includes an option: _Swap command and control key_ which defaults to being enabled on MacOS.

OK, saw it now! So I need to switch that off to obtain the behavior I want, is there a particular reason that the two keys needs to be swapped for MacOS by default. Is it because most apps (other than the terminal) prefers the swapped keys?

**Comment by totaam** [comment]
> is there a particular reason that the two keys needs to be swapped for MacOS by default

Aren't they switched around for most applications already?
ie: in most native MacOS applications copy and paste is `command+c` and `command+v`, is it not?

**Comment by oeway** [comment]
> > is there a particular reason that the two keys needs to be swapped for MacOS by default
> 
> Aren't they switched around for most applications already?
> ie: in most native MacOS applications copy and paste is `command+c` and `command+v`, is it not?

That is true, but one exception is the terminal apps which uses `control+c` for sending termination signal and `command+c` for copy. Not sure if there is a way to differentiate terminate from other types of applications somehow. Maybe we can make an exception for `control+c` and `control+d` signal from macOS keyboard and convert to `ctrl+c` automatically?

**Comment by totaam** [comment]
> Not sure if there is a way to differentiate terminate from other types of applications somehow

There is, we could use the `class-instance` attribute and match `term` (for `xterm` and all the other terminal applications).

But per-application swapping would be hell to implement: what if you switch application whilst one of those two keys is held down!

**Comment by oeway** [comment]
> There is, we could use the class-instance attribute and match term (for xterm and all the other terminal applications).
> But per-application swapping would be hell to implement: what if you switch application whilst one of those two keys is held down!

I understand, so perhaps it should not be done in the client directly, but rather allow the user to customize. If we want to give such a list, where should I change?


After swapping command and control, the `control` won't be used anyway, would it make sense to map both `command` and `control` key to `ctrl`?

**Comment by totaam** [comment]
> I understand, so perhaps it should not be done in the client directly

If anywhere, it belongs in the client.

> After swapping command and control, the control won't be used anyway

Why not? It is mapped (to `Alt_L` IIRC) and so it will be used if applications listen for it.

**Comment by oeway** [comment]
> Why not? It is mapped (to Alt_L IIRC) and so it will be used if applications listen for it.

The mac keyboard has the `option` key which is typically used as `alt`, can't we use `option` for `alt`?

**Comment by totaam** [comment]
> SO you mean client.js?

See `translate_modifiers` and `do_keyb_process`.
The latter is very ugly and brittle.

TBH, I have no idea how things really work on a mac, I only use a virtual machine which already does some key translation.
I'm probably not the best person to be making those changes.

**Comment by oeway** [comment]
OK, no worries, I will hack it around for my own application then.
