### ISSUE TITLE
Too many debug message makes the dev tool laggy

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#82]
When open the chrome dev tool, it's almost impossible to use because too many debug message is being printed.

Not sure what's the best way to do this, but if I comment out the console.debug in the `debug_buffer_event` (in `MediaSourceUtil.js`), it becomes much better.

```js
			function debug_buffer_event(event) {
// 				const msg = ""+element_type+" buffer "+event;
// 				console.debug(msg);
			}
```

Maybe we need some sort of debug flag to switch off the debug message entirely so it doesn't appear normally.

**Comment by totaam** [comment]
Ouch. That's bad.
Does the commit above fix things?

**Comment by oeway** [comment]
I confirm this fixes the issue, thanks!
