### ISSUE TITLE
Cursor is huge and pixelated

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#86]
The cursor becomes huge and pixelated in MacOS (10.14.6) chrome:

![IMG_6739](https://user-images.githubusercontent.com/478667/127774244-7027eb1e-3ccf-4ae4-95aa-75e6d51d2bf0.jpg)

Presumably coming from a recent commit here: https://github.com/Xpra-org/xpra-html5/commit/2cd707131e4604e5851f53bb1fb489c3384063b0#diff-a1e1b4b2d88047676266027b42a2355508ead06a6ca7ace30ec269d7e9b1d053

**Comment by totaam** [comment]
Yes, the cursor is now scaled because the browser does not do this automatically when you zoom in.
It doesn't make sense to keep the cursor at a fixed size (try 400% with a terminal cursor to see what I mean).
I had forgotten to also update the hotspot: 5f7df9f6fc9e8ed5d8bc14281a8d78f6717cb28b

Now, why it looks pixelated on your system is probably because you use fractional scaling but I have tried the same here with google-chrome using difficult ratios like 110% and the cursor was crisp every time.
Does db4fb71f4f66643078d378a24f33e90867b80c08 help?

If not, we may have to avoid doing fractional scaling on some platforms like macos and / or Safari. (perhaps round the value to the nearest int on those platforms)

**Comment by oeway** [comment]
Do you mean this is intended? But I was use it without any zoom (100%), it looks like this for text:
![image](https://user-images.githubusercontent.com/478667/127776711-b212d4b8-953e-4a1a-905d-4c7215b3a462.png)

A bit wired, especially when it switch between the native cursor which is very small and the remote cursor which is huge.

**Comment by totaam** [comment]
Without zoom should not have changed anything:
https://github.com/Xpra-org/xpra-html5/blob/db4fb71f4f66643078d378a24f33e90867b80c08/html5/js/Window.js#L1087

But perhaps Safari does something weird and returns a different value?
Can you check it?

**Comment by oeway** [comment]
> Without zoom should not have changed anything:
> https://github.com/Xpra-org/xpra-html5/blob/db4fb71f4f66643078d378a24f33e90867b80c08/html5/js/Window.js#L1087
> 
> But perhaps Safari does something weird and returns a different value?
> Can you check it?
> Your cursor looks twice as big as it should be.

I just checked, the default value for 100% zoom in  macOS browsers including Chrome/FireFox/Safari are `window.devicePixelRatio=2`.

**Comment by oeway** [comment]
Also see here: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

> The string mqString is set up to be the media query itself. The media query, which begins as (resolution: 1dppx) (for standard  displays) or (resolution: 2dppx) (for Retina/HiDPI displays), checks to see if the current display resolution matches a specific  number of device dots per px.

I have a Retina/HiDPI displays display.

**Comment by totaam** [comment]
`mqString` - what is this?
There is no reference to it on that page at all! I think this documentation is missing something.

**Comment by oeway** [comment]
Well, I did some more search, it seems there isn't a reliable way to determine whether devicePixelRatio = 2 means a retina display or zoom level 200%.

I would perhaps restore the previous behavior so it at least works when the zoom level is 100% for all cases.

**Comment by totaam** [comment]
> I would perhaps restore the previous behavior so it at least works when the zoom level is 100% for all cases.

I would rather not penalize the other platforms.
How about the [detect-zoom](https://github.com/tombigel/detect-zoom) library I added above, does that work your mac?

**Comment by oeway** [comment]
As I understand it, it's not platform dependent but rather display dependent. It is rather common to have high density display for all other platform nowadays.

**Comment by oeway** [comment]
@totaam I just tried your new works, unfortunately, it doesn't work, neither for FireFox, nor Chrome.

With 100% zoom, in Firefox it said:
```
detectZoom.zoom() === 2
detectZoom.device() === 2
```

In Chrome (100% zoom):
```
detectZoom.device() ===  2.96
detectZoom.zoom() === 1.48
```

**Comment by oeway** [comment]
@totaam Please note that my edited comment above, it's not only for MacOS, it also happens for Windows. As I mentioned, it's rather display dependent.

**Comment by oeway** [comment]
BTW, a naive question, why don't we use the native cursor via css sytle? Assuming we can get that type of info from the server, why not just do something like: `document.body.style.cursor = 'wait'`?

**Comment by totaam** [comment]
> it also happens for Windows

From what I am seeing during testing and from your data, it isn't so much a problem on other platforms.
And scaling gets us closer to the intended size generally.

> why don't we use the native cursor

For at least three reasons:
* applications can use custom cursors without a name
* the X11 name doesn't necessarily map well to an html5 cursor
* using named cursors doesn't allow us to specify the size

**Comment by totaam** [comment]
Once again, it seems that there is no sane API we can use to guess the correct scaling to use.
